### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by mherreral** [ComparativeGenomicsToolkit/hal#105]
Hello there!
I ran "make" and it ended with an error, the output is the following:

make[1]: se ingresa al directorio `/home/mherreral/apps/hal_/hal/api'
h5c++  -MM -MT /home/mherreral/apps/hal_/hal/objs/api/impl/halAlignmentInstance.o -O3 -g -Wall -funroll-loops -DNDEBUG -I/home/mherreral/apps/sonLib_/sonLib/lib -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -I /home/mherreral/apps/hal_/hal/api/inc -Iimpl -Iinc -I /home/mherreral/apps/hal_/hal/liftover/inc -Ihdf5_impl -Immap_impl -c impl/halAlignmentInstance.cpp >impl/halAlignmentInstance.depend
h5c++  -O3 -g -Wall -funroll-loops -DNDEBUG -I/home/mherreral/apps/sonLib_/sonLib/lib -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -I /home/mherreral/apps/hal_/hal/api/inc -Iimpl -Iinc -I /home/mherreral/apps/hal_/hal/liftover/inc -Ihdf5_impl -Immap_impl -c impl/halAlignmentInstance.cpp -o /home/mherreral/apps/hal_/hal/objs/api/impl/halAlignmentInstance.o
In file included from mmap_impl/mmapAlignment.h(4),
                 from impl/halAlignmentInstance.cpp(12):
mmap_impl/mmapFile.h(153): error: more than one instance of overloaded function "std::to_string" matches the argument list:
            function "std::to_string(long long)"
            function "std::to_string(unsigned long long)"
            function "std::to_string(long double)"
            argument types are: (size_t)
          throw hal_exception("mmap file is full, specify file size larger than " + std::to_string(_fileSize));
                                                                                    ^

/usr/include/c++/4.4.7/bits/stl_vector.h(1051): error: argument of type "hal_index_t={int64_t={long}}" is incompatible with parameter of type "hal::Genome *const &"
          { _M_fill_assign(__n, __val); }
                                ^
          detected during:
            instantiation of "void std::vector<_Tp, _Alloc>::_M_assign_dispatch(_Integer, _Integer, std::__true_type) [with _Tp=hal::Genome *, _Alloc=std::allocator<hal::Genome *>, _Integer=hal_index_t={int64_t={long}}]" at line 395
            instantiation of "void std::vector<_Tp, _Alloc>::assign(_InputIterator, _InputIterator) [with _Tp=hal::Genome *, _Alloc=std::allocator<hal::Genome *>, _InputIterator=hal_index_t={int64_t={long}}]" at line 195 of "/home/mherreral/apps/hal_/hal/api/inc/halGenome.h"

compilation aborted for impl/halAlignmentInstance.cpp (code 2)
make[1]: *** [/home/mherreral/apps/hal_/hal/objs/api/impl/halAlignmentInstance.o] Error 2
make[1]: se sale del directorio `/home/mherreral/apps/hal_/hal/api'
make: *** [api.libs] Error 2

**Comment by diekhans** [comment]
I suspect this is due to the over version of C++ you are using.
Try 4.8.5 or newer.

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
