### ISSUE TITLE
hal2assemblyHub no longer works

### ISSUE THREAD

**Issue by diekhans** [ComparativeGenomicsToolkit/hal#109]
hal2assemblyHub still depends on jobTree, which is not maintained.  Also, it does not have tests, which allowed it to go stale.

Port it to Toil and add tests.

**Comment by diekhans** [comment]
@nathanweeks, would you be able to fork and lead the work, I can advise I have higher priority task I need to focus on and can't actually dive in for a while.

**Comment by diekhans** [comment]
converting jobTree to Toil is the biggest task.    We could do a python2 port to Toil and then a py3 port once that is working.

**Comment by nathanweeks** [comment]
I don't have experience with the toil API, but I'll take a look at the code & gauge the level of effort given my ability. Maybe the py27-docker branch mentioned in https://github.com/ComparativeGenomicsToolkit/hal/issues/108 will come in handy after all :-)

**Comment by diekhans** [comment]
@nathanweeks, feel free to ask away.    Thinking about it a bit more, maybe doing the python2 Toil is a distraction.  There is nothing I see that will cause any hard python3 problems.

**Comment by glennhickey** [comment]
@nathanweeks I just merged in a few changes to hal2assemblyHub.py in #110 to try to get it running in Python3.  Unfortunately, I can't guarantee that all the options work, but it's probably still worth a try.  Feel free to raise specific issues for anything that comes up.

**Comment by diekhans** [comment]
Glenn fixed this in #110

**Comment by nathanweeks** [comment]
@glennhickey Thanks for doing the heavy lifting! I'll build a new container image & test.
