### ISSUE TITLE
--splitBySequence, --refTargets or --refSequence required

### ISSUE THREAD

**Issue by fenderglass** [ComparativeGenomicsToolkit/hal#117]
Hi,

I am using HAL tools as a part of Ragout pipeline. It seems that there have been some changes in the command line API, leading to an error with hal2mafMP.py (https://github.com/fenderglass/Ragout/issues/60)

`--splitBySequence, --refTargets or --refSequence required`

This is the command line I was using with the previous versions:

`hal2mafMP hal_file maf_file --noAncestors --numProc 10 --refGenome ref_genome --targetGenomes list_of_genomes`

Is this the expected behaviour? Exporting all genomes without specifying target regions seems to be a standard use case.

Thanks,
Mikhail

**Comment by diekhans** [comment]
we should be able to fix this...

**Comment by glennhickey** [comment]
Yeah, sorry about that.  I took a quick pass at resuscitating a couple of the python scripts in #110, and I added that error message then.  The workaround now is to use `--splitBySequence` and cat the output together, but it needs to be fixed to support your old command line.

**Comment by fenderglass** [comment]
Thanks!

One potential issue with `--splitBySequence` I can see is that if the reference genome has 1000+ sequences (e.g. is a draft assembly) - then one can hit the OS open files limit (often 1024). Probably, should not be an issue if hal2MafMP opens and closes the generated maf files sequentially.

**Comment by diekhans** [comment]
@fenderglass it only keeps one MAF open at a time

**Comment by diekhans** [comment]
@fenderglass if you would like to tests https://github.com/ComparativeGenomicsToolkit/hal/tree/issues/117/hal2mafSplit

that would be appreciated

**Comment by fenderglass** [comment]
Thanks a lot, guys! I will give it a test and get back soon.

**Comment by bernard-kim** [comment]
Hi all, 

I'm having an issue with the new ```hal2mafMP.py``` that occurs across different alignments (fish, drosophila). I'm using a fresh installation from GitHub into a Conda environment with Python 3.7.6, running Cactus/HAL/CAT in local binaries mode. I'm not having issues running the tools. I believe I have the latest version of ```hal2mafMP.py```: I do not get the required argument error mentioned discussed previously.

This time the error is:
```hal exception caught: Invalid range specified for convertGenome```

Followed by:
```multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/bernardkim/miniconda3/envs/cactus/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/bernardkim/miniconda3/envs/cactus/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/bernardkim/miniconda3/envs/cactus/lib/python3.7/site-packages/hal/stats/halStats.py", line 28, in runShellCommand
    (command, sts))
RuntimeError: Command: hal2maf grimshawi.hal grimshawi.maf --unique --refGenome grimshawiref --refSequence NW_001976516.1 --start 4274650 --length 54 --targetGenomes grimshawi,grimshawiref --noAncestors exited with non-zero status 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bernardkim/miniconda3/envs/cactus/bin/hal2mafMP.py", line 332, in <module>
    sys.exit(main())
  File "/home/bernardkim/miniconda3/envs/cactus/bin/hal2mafMP.py", line 329, in main
    runParallelSlices(args)
  File "/home/bernardkim/miniconda3/envs/cactus/bin/hal2mafMP.py", line 190, in runParallelSlices
    runParallelShellCommands(sliceCmds, options.numProc)
  File "/home/bernardkim/miniconda3/envs/cactus/lib/python3.7/site-packages/hal/stats/halStats.py", line 43, in runParallelShellCommands
    result.get(20000000)
  File "/home/bernardkim/miniconda3/envs/cactus/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
RuntimeError: Command: hal2maf grimshawi.hal grimshawi.maf --unique --refGenome grimshawiref --refSequence NW_001976516.1 --start 4274650 --length 54 --targetGenomes grimshawi,grimshawiref --noAncestors exited with non-zero status 1
```

The script works fine when using ```---splitBySequence``` and concatenating the files manually.

**Comment by Rusfell** [comment]
I meet this error too:
hal exception caught: Invalid range specified for convertGenome

have you fixed this?

> Hi all,
> 
> I'm having an issue with the new `hal2mafMP.py` that occurs across different types and subsets of alignments (fish, drosophila). I'm using a fresh installation from GitHub into a Conda environment with Python 3.7.6, running Cactus/HAL/CAT in local binaries mode. I'm not having issues running those tools. I believe I have the latest version of `hal2mafMP.py`: I do not get the required argument error mentioned discussed previously.
> 
> The command is:
> `hal2mafMP.py --numProc $(nproc) --noAncestors --refGenome ref_genomes_list --targetGenomes target_genomes_list alignment.hal alignment.maf`
> 
> This time the error is:
> `hal exception caught: Invalid range specified for convertGenome`
> 
> Followed by:
> 
> ```
> """
> Traceback (most recent call last):
>   File "/home/bernardkim/miniconda3/envs/cactus/lib/python3.7/multiprocessing/pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "/home/bernardkim/miniconda3/envs/cactus/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
>     return list(map(*args))
>   File "/home/bernardkim/miniconda3/envs/cactus/lib/python3.7/site-packages/hal/stats/halStats.py", line 28, in runShellCommand
>     (command, sts))
> RuntimeError: Command: hal2maf grimshawi.hal grimshawi.maf --unique --refGenome grimshawiref --refSequence NW_001976516.1 --start 4274650 --length 54 --targetGenomes grimshawi,grimshawiref --noAncestors exited with non-zero status 1
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/bernardkim/miniconda3/envs/cactus/bin/hal2mafMP.py", line 332, in <module>
>     sys.exit(main())
>   File "/home/bernardkim/miniconda3/envs/cactus/bin/hal2mafMP.py", line 329, in main
>     runParallelSlices(args)
>   File "/home/bernardkim/miniconda3/envs/cactus/bin/hal2mafMP.py", line 190, in runParallelSlices
>     runParallelShellCommands(sliceCmds, options.numProc)
>   File "/home/bernardkim/miniconda3/envs/cactus/lib/python3.7/site-packages/hal/stats/halStats.py", line 43, in runParallelShellCommands
>     result.get(20000000)
>   File "/home/bernardkim/miniconda3/envs/cactus/lib/python3.7/multiprocessing/pool.py", line 657, in get
>     raise self._value
> RuntimeError: Command: hal2maf grimshawi.hal grimshawi.maf --unique --refGenome grimshawiref --refSequence NW_001976516.1 --start 4274650 --length 54 --targetGenomes grimshawi,grimshawiref --noAncestors exited with non-zero status 1
> ```
> 
> The script works fine when using `---splitBySequence` and concatenating the files manually.
