### ISSUE TITLE
Installation Error (Makefile:17: api.progs)

### ISSUE THREAD

**Issue by imk1** [ComparativeGenomicsToolkit/hal#120]
I am trying to install the HAL Format API and am getting the following error:
collect2: error: ld returned 1 exit status
make[1]: *** [../rules.mk:32: ../bin/halHdf5Tests] Error 1
make[1]: Leaving directory '[directory with hal]/hal/api'
make: *** [Makefile:17: api.progs] Error 2
I have successfully installed hal on another machine, so I am not sure why it will not install now.
My path includes [directory with hal]/hal/hdf5-1.10.1/hdf5/bin.
My h5prefix=-prefix is [directory with hal]/hal/hdf5-1.10.1/hdf5.
Thanks for helping me figure this out!

**Comment by diekhans** [comment]
Hi Irene,

Please attach the entire output file to this ticket.  Also, please up sonlib
and please make sure you are using the one from

  git@github.com:ComparativeGenomicsToolkit/sonLib.git

not an older repo

**Comment by imk1** [comment]
I am not sure what I had before, but I just downloaded and compiled the version you suggested, and now things seem to be working.  Thanks!
