### ISSUE TITLE
Using --inBedVersion in Latest Version of halLiftover

### ISSUE THREAD

**Issue by imk1** [ComparativeGenomicsToolkit/hal#121]
An older version of halLiftover had an --inBedVersion that the current version does not seem to have.  How can I incorporate that option?  I have a file that is > 3 columns (it's in narrowPeak format, so it's 10 columns), and I want the 4th column information to be maintained in the halLiftover outputs (I do not need beyond column 4).  Thanks!

**Comment by diekhans** [comment]
Hi Irene,

It now expects standard bed columns up to BED 12.  All other
columns after that are just passed through.  Does this work for
you?  This change while fix bugs in the bed code, we can easily
put if back if need non-standard columns on < 12 standard columns.

**Comment by diekhans** [comment]
We can add this back in.

**Comment by diekhans** [comment]
halLiftover now has --bedType N which specifies the number of standard columns.  So you would use --bedType 6

This is different than the previous version, it that it doesn't remove columns on output.  

As always, yell if this doesn't work.

**Comment by imk1** [comment]
That works!  Thanks you so much!

**Comment by imk1** [comment]
--bedType does seem to work.  However, it sometimes concatenates column ends to each other.  For example, I tried using --bedType 4 on a bed file that had 10 columns (but only the 1st 4 were in proper bed format).  The 1st region's output was what I expected.  The 2nd region's output contained ortholog of region 2 (4 columns) followed by columns 5-10 of region 1 followed by columns 5-10 of region 2.  The 3rd region's output contained ortholog of region 3 (for columns) followed by columns 5-10 of region 1, followed by columns 5-10 of region 2, followed by columns 5-10 of region 3.  Might you be able to fix this or warn users that this can happen if bedType < number of columns?  Thanks!

**Comment by diekhans** [comment]
Hi Irene,

Could you attach a files with one of a few input BED row and cooresponding
bad output rows?

**Comment by imk1** [comment]
Here is an example of input:
chr1    778515  778976  peak1   1000    .       18.28586        95.71721        92.35014        211
chr1    827361  827676  peak2   895     .       8.87136 32.58973        30.14121        162
chr1    869666  870264  peak3   1000    .       14.01752        90.72202        87.42883        235
chr1    869666  870264  peak4   1000    .       5.17879 18.37887        16.19362        494

Here is the corresponding output:
chr5    129908460       129908461       peak1   1000    .       18.28586        95.71721        92.35014        211
chr5    129908739       129908784       peak1   1000    .       18.28586        95.71721        92.35014        211
chr5    33724613        33724626        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724601        33724613        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724583        33724596        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724581        33724582        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724559        33724581        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724556        33724559        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724522        33724540        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724514        33724522        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724499        33724512        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724498        33724499        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724495        33724498        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724478        33724480        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724473        33724478        peak3   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235
chr5    33724613        33724626        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724601        33724613        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724583        33724596        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724581        33724582        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724559        33724581        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724556        33724559        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724522        33724540        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724514        33724522        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724499        33724512        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724498        33724499        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724495        33724498        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724478        33724480        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494
chr5    33724473        33724478        peak4   1000    .       18.28586        95.71721        92.35014        211     895     .       8.87136 32.58973
        30.14121        162     1000    .       14.01752        90.72202        87.42883        235     1000    .       5.17879 18.37887        16.19362
        494

**Comment by diekhans** [comment]
could you try out this branch and see if it fixes all your problems?

https://github.com/ComparativeGenomicsToolkit/hal/tree/issues/121/extra-columns-copied

**Comment by imk1** [comment]
It does not seem to solve the problem.

Here is the input file I used for testing:
[testInput.txt](https://github.com/ComparativeGenomicsToolkit/hal/files/4506389/testInput.txt)

Here is the output file I got:
[testOutput.txt](https://github.com/ComparativeGenomicsToolkit/hal/files/4506391/testOutput.txt)

**Comment by diekhans** [comment]
Hmm, this is weird.  This looks like the problem I fixed.

Can you tripled check you are running a version with the one-line
change to liftover/impl/halBedLine.cpp 

   https://github.com/ComparativeGenomicsToolkit/hal/pull/126/files

it adds the line:
  _extra.clear();

if you have this, then can I get access to your hal file? or
maybe just halExtract the region?

**Comment by imk1** [comment]
The _extra.clear(); line is in liftover/impl/halBedLine.cpp.

I am using the Zoonomia (200 Mammals Project) hal file.

**Comment by diekhans** [comment]
please share the exact command line you are using

**Comment by imk1** [comment]
/home/ikaplow/RegulatoryElementEvolutionProject/src/hal/bin/halLiftover --bedType 4 /data/pfenninggroup/align/mam200/alignment_files/200m-v1.hal Homo_sapiens /home/ikaplow/RegulatoryElementEvolutionProject/src/testInput.txt Mus_musculus /home/ikaplow/RegulatoryElementEvolutionProject/src/testOutput.txt

Thanks for helping me solve this problem!

**Comment by diekhans** [comment]
Thanks back for helping solve this problem!

So I ran your command on the 200m hal and it worked fine, with
all output BED records being 10 columns.

Perhaps a compile problem on your end?

**Comment by imk1** [comment]
Recompiling worked!  Sorry for not thinking to recompile, and thanks so much for fixing this so quickly!
