### ISSUE TITLE
Installing hal

### ISSUE THREAD

**Issue by ashlingcha** [ComparativeGenomicsToolkit/hal#123]
Hi there,
unsure if installation has changed from before - but I'm on ubuntu and tried installing using the following commands:

sudo apt install libhdf5-dev
git clone https://github.com/ComparativeGenomicsToolkit/hal.git
git clone https://github.com/benedictpaten/sonLib.git
pushd sonLib && make && popd
cd hal
make

although when I make hal I get this error: 
`
In file included from ../api/inc/halDnaIterator.h:11:0,
                 from ../api/inc/halColumnIterator.h:13,
                 from ../api/inc/hal.h:67,
                 from tests/halRandomData.h:11,
                 from tests/halRandomData.cpp:7:
../api/inc/halDnaDriver.h: In destructor ‘virtual hal::DnaAccess::~DnaAccess()’:
../api/inc/halDnaDriver.h:24:90: warning: throw will always call terminate() [-Wterminate]
                 throw hal_exception("DnaAccess is dirty, flush() should have been called");
                                                                                          ^
../api/inc/halDnaDriver.h:24:90: note: in C++11 destructors default to noexcept
make[1]: Leaving directory '/home/ubuntu/hal/api'
cd stats && make libs
make[1]: Entering directory '/home/ubuntu/hal/stats'
h5c++  -MM -MT ../objs/stats/impl/halStats.o -I../../sonLib/lib -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -I../api/inc -Iimpl -Iinc -I../liftover/inc -c impl/halStats.cpp >impl/halStats.depend
h5c++  -I../../sonLib/lib -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -I../api/inc -Iimpl -Iinc -I../liftover/inc -c impl/halStats.cpp -o ../objs/stats/impl/halStats.o
In file included from ../api/inc/halDnaIterator.h:11:0,
                 from ../api/inc/halColumnIterator.h:13,
                 from ../api/inc/hal.h:67,
                 from inc/halStats.h:11,
                 from impl/halStats.cpp:8:
../api/inc/halDnaDriver.h: In destructor ‘virtual hal::DnaAccess::~DnaAccess()’:
../api/inc/halDnaDriver.h:24:90: warning: throw will always call terminate() [-Wterminate]
                 throw hal_exception("DnaAccess is dirty, flush() should have been called");
                                                                                          ^
../api/inc/halDnaDriver.h:24:90: note: in C++11 destructors default to noexcept
ar rc ../lib/libHalStats.a ../objs/stats/impl/halStats.o
../lib/libHalStats.a
make[1]: execvp: ../lib/libHalStats.a: Permission denied
../rules.mk:39: recipe for target '../lib/libHalStats.a' failed
make[1]: *** [../lib/libHalStats.a] Error 127
make[1]: Leaving directory '/home/ubuntu/hal/stats'
Makefile:13: recipe for target 'stats.libs' failed
make: *** [stats.libs] Error 2
`
any idea of what I may be doing wrong?
Thanks

**Comment by diekhans** [comment]
Update sonlib to fix this issue.

**Comment by diekhans** [comment]
p.s.  we will get the other sonlib repo deactivated,
ComparativeGenomicsToolkit/sonLib is now the actively
developed version.
