### ISSUE TITLE
Make Error API

### ISSUE THREAD

**Issue by apfenning** [ComparativeGenomicsToolkit/hal#125]
I'm having some issues making HAL. The error follows a long chain, but occurs in API:

cd api && make progs
make[1]: Entering directory `/home/apfennin/bin/enhXspec/hal/api'
h5c++ -prefix=/home/apfennin/bin/enhXspec/hal/hdf5 -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -O3 -g -Wall -funroll-loops -DNDEBUG -I../../sonLib/lib -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -I../api/inc -Iimpl -Iinc -I../liftover/inc -Ihdf5_impl -Immap_impl -I tests -o ../bin/halHdf5Tests ../objs/api/hdf5_tests/hdf5SegmentTypeTest.o ../objs/api/hdf5_tests/hdf5ExternalArrayTest.o ../objs/api/hdf5_tests/allTests.o ../objs/api/hdf5_tests/hdf5SequenceTypeTest.o ../objs/api/hdf5_tests/hdf5DnaTypeTest.o ../objs/api/hdf5_tests/hdf5Test.o  ../lib/libHal.a ../../sonLib/lib/sonLib.a ../../sonLib/lib/cuTest.a 
../objs/api/hdf5_tests/hdf5Test.o: In function `writeNumbers(unsigned long long)':
[...]
/home/apfennin/bin/enhXspec/hal/api/hdf5_impl/hdf5MetaData.cpp:98: undefined reference to `H5::H5Location::createAttribute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, H5::DataType const&, H5::DataSpace const&, H5::PropList const&) const'
/home/apfennin/bin/enhXspec/hal/api/hdf5_impl/hdf5MetaData.cpp:96: undefined reference to `H5::H5Location::removeAttr(char const*) const'
collect2: error: ld returned 1 exit status
make[1]: *** [../bin/halHdf5Tests] Error 1
make[1]: Leaving directory `/home/apfennin/bin/enhXspec/hal/api'
make: *** [api.progs] Error 2

Here are a couple of specifics that could help:

- A colleague of mine has been able to install on the same cluster (CENTOS 7)
- GCC version 5.3.0
- python 3.5.2
- I've successfully installed HAL on another cluster afterwards using the exact same procedure
- hdf5 was successfully installed (and I have verified that the path was properly set)
- I don't have sudo

Thanks for your help!

**Comment by amv33576** [comment]
Hello, I am having the same problem. I can not install hal. I was using an older version of hal, but then the halLiftover was not working properly and clone again the repository to get the fix discussed in another issue (#121 ).  
what I did
(1) set path for hdf5, variables for sonLibRootDir, h5prefix, ENABLE_PHYLOP
then:
$ cd hal/
$ make
cd api && make libs
make[1]: Entering directory `/local/workdir/Mimi/WGA/cactus_env/hal/api'
h5c++ -prefix=/workdir/Mimi/WGA/hdf5 -MM -MT ../objs/api/impl/halAlignmentInstance.o -I../../sonLib/lib -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -DENABLE_PHYLOP -I../../phast/include -I../../phast/src/lib/pcre -I/workdir/Mimi/WGA/cactus_env/clapack/INCLUDE -I/workdir/Mimi/WGA/cactus_env/clapack/F2CLIBS -I../api/inc -Iimpl -Iinc -I../liftover/inc -Ihdf5_impl -Immap_impl -c impl/halAlignmentInstance.cpp >impl/halAlignmentInstance.depend
.....
ar rc ../lib/libHal.a ../objs/api/impl/halAlignmentInstance.o ../objs/api/impl/halGappedTopSegmentIterator.o ../objs/api/impl/halMappedSegment.o ../objs/api/impl/halColumnIterator.o ../objs/api/impl/halSegmentIterator.o ../objs/api/impl/halTopSegment.o ../objs/api/impl/halBottomSegmentIterator.o ../objs/api/impl/halSegmentMapper.o ../objs/api/impl/halValidate.o ../objs/api/impl/halGappedBottomSegmentIterator.o ../objs/api/impl/halTopSegmentIterator.o ../objs/api/impl/halCLParser.o ../objs/api/impl/halRearrangement.o ../objs/api/impl/halPositionCache.o ../objs/api/impl/halCommon.o ../objs/api/impl/halSegment.o ../objs/api/impl/halBottomSegment.o ../objs/api/impl/halGenome.o ../objs/api/hdf5_impl/hdf5Sequence.o ../objs/api/hdf5_impl/hdf5DnaDriver.o ../objs/api/hdf5_impl/hdf5BottomSegment.o ../objs/api/hdf5_impl/hdf5SequenceIterator.o ../objs/api/hdf5_impl/hdf5Genome.o ../objs/api/hdf5_impl/hdf5TopSegment.o ../objs/api/hdf5_impl/hdf5ExternalArray.o ../objs/api/hdf5_impl/hdf5UDCFuseDriver.o ../objs/api/hdf5_impl/hdf5Alignment.o ../objs/api/hdf5_impl/hdf5MetaData.o ../objs/api/mmap_impl/mmapAlignment.o ../objs/api/mmap_impl/mmapGenomeSiteMap.o ../objs/api/mmap_impl/mmapDnaDriver.o ../objs/api/mmap_impl/mmapPerfectHashTable.o ../objs/api/mmap_impl/mmapRbTree.o ../objs/api/mmap_impl/mmapSequence.o ../objs/api/mmap_impl/mmapBottomSegment.o ../objs/api/mmap_impl/mmapFile.o ../objs/api/mmap_impl/mmapGenome.o ../objs/api/mmap_impl/mmapPhf.o ../objs/api/mmap_impl/mmapTopSegment.o 
../lib/libHal.a
**make[1]: execvp: ../lib/libHal.a: Permission denied
make[1]: *** [../lib/libHal.a] Error 127
make[1]: Leaving directory `/local/workdir/Mimi/WGA/cactus_env/hal/api'
make: *** [api.libs] Error 2**

HELP!!!

**Comment by diekhans** [comment]
this indicates you don't have the correct version of sonlib,
which should be obtained from:

  https://github.com/ComparativeGenomicsToolkit/sonLib


an easier way might be to obtain pre-compiled hal programs from:
   https://github.com/ComparativeGenomicsToolkit/cactus/releases/download/v1.0.0/cactus-bin-v1.0.0.tar.gz

**Comment by amv33576** [comment]
Thanks for your response, I updated the sonLib but I am still having problems. I got this error message:

**cd phyloP && make progs**
make[1]: Entering directory `/local/workdir/Mimi/WGA/cactus_env/hal/phyloP'
h5c++ -prefix=/workdir/Mimi/WGA/hdf5 -MM -MT ../objs/phyloP/impl/halPhyloPMain.o -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -O3 -g -Wall -funroll-loops -DNDEBUG -I../../sonLib/lib -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -DENABLE_PHYLOP -I../../phast/include -I../../phast/src/lib/pcre -I/workdir/Mimi/WGA/cactus_env/clapack/INCLUDE -I/workdir/Mimi/WGA/cactus_env/clapack/F2CLIBS -I../api/inc -Iimpl -Iinc -I../liftover/inc -I../liftover/inc -c impl/halPhyloPMain.cpp >impl/halPhyloPMain.depend
h5c++ -prefix=/workdir/Mimi/WGA/hdf5 -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -O3 -g -Wall -funroll-loops -DNDEBUG -I../../sonLib/lib -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -DENABLE_PHYLOP -I../../phast/include -I../../phast/src/lib/pcre -I/workdir/Mimi/WGA/cactus_env/clapack/INCLUDE -I/workdir/Mimi/WGA/cactus_env/clapack/F2CLIBS -I../api/inc -Iimpl -Iinc -I../liftover/inc -I../liftover/inc -c impl/halPhyloPMain.cpp -o ../objs/phyloP/impl/halPhyloPMain.o
h5c++ -prefix=/workdir/Mimi/WGA/hdf5 -MM -MT ../objs/phyloP/impl/halPhyloPBed.o -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -O3 -g -Wall -funroll-loops -DNDEBUG -I../../sonLib/lib -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -DENABLE_PHYLOP -I../../phast/include -I../../phast/src/lib/pcre -I/workdir/Mimi/WGA/cactus_env/clapack/INCLUDE -I/workdir/Mimi/WGA/cactus_env/clapack/F2CLIBS -I../api/inc -Iimpl -Iinc -I../liftover/inc -I../liftover/inc -c impl/halPhyloPBed.cpp >impl/halPhyloPBed.depend
h5c++ -prefix=/workdir/Mimi/WGA/hdf5 -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -O3 -g -Wall -funroll-loops -DNDEBUG -I../../sonLib/lib -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -DENABLE_PHYLOP -I../../phast/include -I../../phast/src/lib/pcre -I/workdir/Mimi/WGA/cactus_env/clapack/INCLUDE -I/workdir/Mimi/WGA/cactus_env/clapack/F2CLIBS -I../api/inc -Iimpl -Iinc -I../liftover/inc -I../liftover/inc -c impl/halPhyloPBed.cpp -o ../objs/phyloP/impl/halPhyloPBed.o
impl/halPhyloPBed.cpp: In member function 'virtual void hal::PhyloPBed::visitLine()':
impl/halPhyloPBed.cpp:48:22: error: 'struct hal::BedLine' has no member named '_version'
         if (_bedLine._version <= 9) {
                      ^
make[1]: *** [../objs/phyloP/impl/halPhyloPBed.o] Error 1
make[1]: Leaving directory `/local/workdir/Mimi/WGA/cactus_env/hal/phyloP'
make: *** [phyloP.progs] Error 2


Thanks

**Comment by diekhans** [comment]
Looks like I broke phyloP support with some recent changes. This will be fixed
today.

**Comment by diekhans** [comment]
fixed by https://github.com/ComparativeGenomicsToolkit/hal/pull/128
