### ISSUE TITLE
halLodExtract

### ISSUE THREAD

**Issue by jasonsydes** [ComparativeGenomicsToolkit/hal#132]
Hi there!  I'm trying to run hal2assemblyHub.py, and I'm seeing a failure.  I have two HAL files, one from a cactus alignment of 13 species, and another from a cactus alignment of 84 species.  The former results in the following error (edited to remove full paths for brevity):
```
RuntimeError: Command: halLodExtract outdir/out.hal outdir/lod/out_lod_705.hal 39.0625 --minSeqFrac 0.500000 exited with non-zero status -11
```
The latter results in:
```
RuntimeError: Command: halLodExtract outdir/out.hal outdir/lod/out_lod_1265.hal 97.65625 --minSeqFrac 0.500000 exited with non-zero status -11
```
I tried running the first halLodExtract above command by hand, and it produces the following output: 
```
tree = (((lepOcu2_gar:1,(danRer7_zebrafish:1,((oryLat2_ricefish:1,xipMac1_platyfish:1)Anc08:1,(gasAcu1_stickleback:1,tetNig2_pufferfish:1)Anc09:1)Anc06:1)Anc04:1)Anc02:1,(latCha1_coelacanth:1,(xenTro3_frog:1,((hg19_human:1,mm10_mouse:1)Anc10:1,(galGal4_chicken:1,anoCar2_lizard:1)Anc11:1)Anc07:1)Anc05:1)Anc03:1)Anc01:1,calMil1_eshark:1)Anc00;
Graph: numBlocks=1080125 numSegs=2190211 minSegs=1 maxSegs=91 totLen=1080125 minLen=1 maxLen=1 totAdjLen=1371044998 minAdjLen=0 maxAdjLen=33252
Graph: numBlocks=1080125 numSegs=2190211 minSegs=1 maxSegs=91 totLen=645317894 minLen=1 maxLen=3408 totAdjLen=120221494 minAdjLen=0 maxAdjLen=13718
Graph: numBlocks=809356 numSegs=1770260 minSegs=1 maxSegs=91 totLen=645317894 minLen=1 maxLen=7792 totAdjLen=120221494 minAdjLen=0 maxAdjLen=13718
Graph: numBlocks=1263500 numSegs=2732290 minSegs=1 maxSegs=91 totLen=706784971 minLen=1 maxLen=7792 totAdjLen=0 minAdjLen=0 maxAdjLen=0
Command terminated by signal 11
```
It does produce a HAL file that is about 24MB in size, but halValidate says:
```
hal exception caught: HAL API v2.1 incompatible with format v0.0 HAL file.
```
halStats gives the same error.

This is with the v2..1 of hal, and the original HAL alignment file was generated with a version of cactus that was built on Oct 9, 2019.

**Comment by diekhans** [comment]
Hi Jason,

The check is wrong.  We have keep HAL HDF5 backwards compatible for years.  If you
disable the check around compatibleWithVersion(getVersion())) in

        hal/api/hdf5_impl/hdf5Alignment.cpp

I think it should work fine.  I will commit a change to disable this.

Mark
