### ISSUE TITLE
halAddToBranch dumps core

### ISSUE THREAD

**Issue by ybukhman** [ComparativeGenomicsToolkit/hal#164]
I would like to add a genome to the 200-mammal alignment. I am testing this functionality on the evolverMammals dataset by building an alignment without the rat genome and then adding the rat to the mouse branch. Here is my terminal output when I try to run halAddToBranch:

(venv) bash-4.2$ halAddToBranch evolverMammals2.hal \\
\> cactus_add_rat_bottom_Try2/add_rat_bottom.hal cactus_add_rat_top_Try2/add_rat_top.hal \\
\> Anc1 ancMR simMouse_chr6 simRat_chr6 0.271974 0.091589
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 0:
  #000: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5G.c line 321 in H5Gcreate2(): unable to create group
    major: Symbol table
    minor: Unable to initialize object
  #001: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5Gint.c line 157 in H5G__create_named(): unable to create and link to group
    major: Symbol table
    minor: Unable to initialize object
  #002: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5L.c line 1592 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5L.c line 1833 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5L.c line 1639 in H5L__link_cb(): unable to create object
    major: Links
    minor: Unable to initialize object
  #007: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5Oint.c line 2460 in H5O_obj_create(): unable to open object
    major: Object header
    minor: Can't open object
  #008: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5Goh.c line 264 in H5O__group_create(): unable to create group
    major: Symbol table
    minor: Unable to initialize object
  #009: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5Gint.c line 207 in H5G__create(): unable to create group object header
    major: Symbol table
    minor: Unable to initialize object
  #010: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5Gobj.c line 158 in H5G__obj_create(): unable to create group
    major: Symbol table
    minor: Unable to create file
  #011: /home/hdftest/snapshots-hdf5_1_10_6/current/src/H5Gobj.c line 201 in H5G__obj_create_real(): no write intent on file
    major: Object cache
    minor: Bad value
terminate called after throwing an instance of 'H5::FileIException'
Aborted (core dumped)

Any suggestions would be appreciated.

Thanks.

Yury

**Comment by diekhans** [comment]
Someone had a similar error and it appeared to be HAL picking up
a different HDF5 library than it was complied with.  At least it
was resolve by removing the other version of HDF5.

I would highly recommend download the binary, static-linked version
of cactus, which includes HAL.

**Comment by ybukhman** [comment]
Thank you, @diekhans!

When using the pre-built binary, I got a different error, still with a core dump:
(venv) bash-4.2$ halAddToBranch evolverMammals2.hal \
> cactus_add_rat_bottom_Try2/add_rat_bottom.hal cactus_add_rat_top_Try2/add_rat_top.hal \
> Anc1 ancMR simMouse_chr6 simRat_chr6 0.271974 0.091589
terminate called after throwing an instance of 'hal_exception'
  what():  When copying bottom segments from ancMR to ancMR: expected destination sequence ancMRrefChr2 for segment # 27247 but got ancMRrefChr3
Aborted (core dumped)

**Comment by ybukhman** [comment]
I have redone the whole exercise from the beginning and it worked this time. The error in the previous attempt was likely that I forgot to use the --root option when building the bottom alignment.
