### ISSUE TITLE
Cannot run hal2assemblyHub.py with minimal input requirement

### ISSUE THREAD

**Issue by drosophila92** [ComparativeGenomicsToolkit/hal#166]
Hi there,

I'm having trouble using the hal2assemblyHub.py from our computing cluster.

I tried to run hal2assemblyHub.py on a pre-existing .hal file called `group_2_3.hal` and output my results in a pre-existing directory called `group_2_3_assemblyHub`. Here is the code I use:

`hal2assemblyHub.py group_2_3.hal group_2_3_assemblyHub --lod`

I got the error message as follows:
>Traceback (most recent call last):
  File "/software/hal/2.1/lssc0-linux/hal/bin/hal2assemblyHub.py", line 24, in <module>
    from sonLib.bioio import system, getTempFile
ImportError: No module named sonLib.bioio

I contacted support team of our cluster and they said the dependency sonLib has been installed and put in the correct path, but that did not solve my problem.

Some related information:
* hal module used: hal/2.1
* cluster OS: Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-112-generic x86_64)

Just let me know if you need anything else to identify the problem. Thank you for your time!

Yige

**Comment by glennhickey** [comment]
sonLib's parent directory needs to be in `PYTHONPATH` for this to work.  ex
```
git clone https://github.com/ComparativeGenomicsToolkit/sonLib.git
export PYTHONPATH=$(pwd):PYTHONPATH
```

**Comment by drosophila92** [comment]
Thanks for your feedback! A quick follow up question: in order to modify `PYTHONPATH` on the cluster, do I need to have root privilege to make the change? I tried the following when I logged into cluster but the `PATHONPATH` remains empty before and after.

```

echo $PYTHONPATH
export PYTHONPATH=$(pwd):PYTHONPATH
echo $PYTHONPATH
```
Yige

**Comment by glennhickey** [comment]
I made a typo above, it should be export `PYTHONPATH=$(pwd):$PYTHONPATH`, but I don't think that affects the present issue.  Unfortunately, I have no idea why export is not working for you.  I've never heard of requiring root to set an environment variable before, but anything's possible I guess.  Perhaps the type of shell you're running is somehow restricted or doesn't support it.  I think you will have to consult your local IT.

**Comment by drosophila92** [comment]
Thanks for answering my question! After checking with the our local IT I resolved the `PYTHONPATH` problem. However I'm still unable to run `hal2assemblyHub.py` due to a different error. I'll start a new issue-report post and describe my question there.

Yige
