### ISSUE TITLE
fatal error: fit_column.h: No such file or directory

### ISSUE THREAD

**Issue by annabananakobana** [ComparativeGenomicsToolkit/hal#170]
Hi there, 

Getting the following error during install:

`/nobackup/*/cactus/cactus_env/cactus/clapack/F2CLIBS -I../api/inc -Iimpl -Iinc -I../liftover/inc -I../liftover/inc -c impl/halPhyloPMain.cpp >impl/halPhyloPMain.depend
In file included from impl/halPhyloPMain.cpp:9:0:
inc/halPhyloP.h:18:24: fatal error: fit_column.h: No such file or directory
 #include "fit_column.h"
                        ^
compilation terminated.
make[1]: *** [../objs/phyloP/impl/halPhyloPMain.o] Error 1
make[1]: Leaving directory '/scale_wlg_nobackup/filesets/nobackup/*/cactus/cactus_env/cactus/hal/phyloP'
make: *** [phyloP.progs] Error 2`

Renaming the library files, for example `phast_fit_column.h` to `fit_column.h` runs into further errors:

`In file included from /scale_wlg_persistent/filesets/opt_cray/cm_shared/opt/gcc/6.1.0/snos/include/g++/iterator:66:0,
                 from /scale_wlg_persistent/filesets/opt_cray/cm_shared/opt/gcc/6.1.0/snos/include/g++/backward/hashtable.h:63,
                 from inc/halPhyloP.h:19,
                 from impl/halPhyloPMain.cpp:9:
/scale_wlg_persistent/filesets/opt_cray/cm_shared/opt/gcc/6.1.0/snos/include/g++/backward/hashtable.h:1129:3: error: template with C linkage
   template<class _Val, class _Key, class _HF, class _Ex, class _Eq, class _All>
   ^~~~~~~~
make[1]: *** [../objs/phyloP/impl/halPhyloPMain.o] Error 1
make[1]: Leaving directory /scale_wlg_nobackup/filesets/nobackup/xx/x_hal/hal/phyloP
make: *** [phyloP.progs] Error 2`

Suspecting a systematic error related to compilers.

Any suggestions?

Thanks in advance,
Anna

**Comment by diekhans** [comment]
http://compgen.cshl.edu/phast/downloads/phast.v1_5.tgz contains phast/include/fit_column.h
It looks like it was renamed in github, but that is not in a release.  Please download version 1.5

**Comment by annabananakobana** [comment]
Thanks, that got it! :)
