### ISSUE TITLE
halStats: command not found

### ISSUE THREAD

**Issue by annabananakobana** [ComparativeGenomicsToolkit/hal#171]
Trying to extract the guide tree from a hal file. Successfully installed the toolkit [https://github.com/ComparativeGenomicsToolkit/hal](url), however, halStats is not recognised as a command. 
`-bash: halStats: command not found`
Anyone else had this issue?

**Comment by diekhans** [comment]
I suspect the hal bin directory is not in your PATH.

**Comment by annabananakobana** [comment]
Yeah, doesn't look like it wrote to the PATH from my script. Fixed it now! Cheers!
