### ISSUE TITLE
hal2fasta and H5::DataSetIException

### ISSUE THREAD

**Issue by annabananakobana** [ComparativeGenomicsToolkit/hal#172]
Trying to extract fasta sequences from the 200_mammal alignment
`hal2fasta 200m-v1.hal Rattus_norvegicus --hdf5CacheBytes 0 > genomes_extracted_from_hal/Rattus_norvegicus.fa`

However, I keep running into the following error:

`HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5Dio.c line 171 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 544 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 2050 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 3405 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: H5Z.c line 1374 in H5Z_pipeline(): filter returned failure during read
    major: Data filters
    minor: Read failed
  #005: H5Zdeflate.c line 123 in H5Z_filter_deflate(): inflate() failed
    major: Data filters
    minor: Unable to initialize object
terminate called after throwing an instance of 'H5::DataSetIException'
./extract_genomes_from_hal.sh: line 15: 67615 Aborted`

I have tried the following:
1. Set PATH variables to hal and hdf5
2. Updated hdf5 to `HDF5/1.10.5-gimpi-2020a`
3. Calling `halStats` (results in a similar error)

Could this be a disparity in versioning between hdf5 and hal? I ran the hal build this week, so should all be the most recent versions. Additionally, `halStats` worked fine yesterday, so not sure what is going on here!

Any suggestions would be greatly appreciated!

Cheers,
Anna

**Comment by diekhans** [comment]
Hi Anna,

I just tried the command you ran on the 200m alignment and it finished fine,

The md5 on my file 200m HAL  is 75c61424a6adb48a2ed1d7d6e53a1633

does that match yours?

Mark

**Comment by diekhans** [comment]
We have  HDF5 1.8.12;  the newer HDF5 should be backwards compatible, however, is it easy for you to try rebuiild with the older version?

**Comment by glennhickey** [comment]
Is the binary release an option here?

https://github.com/ComparativeGenomicsToolkit/cactus/releases/download/v1.2.3/cactus-bin-v1.2.3.tar.gz

**Comment by annabananakobana** [comment]
Thanks team, yeah, that checksum appears to be the problem! I am re-downloading the hal for a retry.

**Comment by annabananakobana** [comment]
Is there a way we can get the checksums for the hal files? I need to cross-check for the 600-way and the avian alignment.

**Comment by diekhans** [comment]
here they are, the file names are changed, as we are setting up a
canonical download location:

75c61424a6adb48a2ed1d7d6e53a1633  242-mammalian-2020.hal
baefcc9713674e2b4cd8156b7186aec6  363-avian-2020.hal
8dcf28e4d475db4af66caa026090e10e  605-vertebrate-2020.hal

**Comment by annabananakobana** [comment]
Excellent thanks! I suspect these are also located in the original repo (https://alignment-output.s3.amazonaws.com/)?

**Comment by diekhans** [comment]
They are the same files as on AWS, just renamed to make them clearer.   We
are setting up another download location.
