### ISSUE TITLE
halReplaceGenome HDF5 error

### ISSUE THREAD

**Issue by pbandjanet** [ComparativeGenomicsToolkit/hal#175]
I am trying to replace a genome from the 242-way mammalian alignment from the cactus preprint (ex. update pt5 to pt6). When I run halReplaceGenome, I am getting the following error:

```
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: H5D.c line 151 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5VLcallback.c line 1869 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: H5VLcallback.c line 1835 in H5VL__dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: H5VLnative_dataset.c line 75 in H5VL__native_dataset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #004: H5Dint.c line 411 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #005: H5L.c line 1804 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #006: H5L.c line 2045 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #007: H5Gtraverse.c line 855 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #008: H5Gtraverse.c line 630 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #009: H5L.c line 1840 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
terminate called after throwing an instance of 'H5::GroupIException'
```

I ran the same sequence of commands on the evolverMammals test set and was able to remove a genome, create a new subtree with a replacement genome, and then replace the genome in the larger tree following the instructions on the wiki. Given the size difference between the test set and the 242-way, I'm guessing that I might need to fiddle with some of the HDF5 cache size, chunk size, etc. parameters in halReplaceGenome, but have not gotten any of them to work. I would appreciate any suggestions as to what might be going wrong!

**Comment by glennhickey** [comment]
Unless the crash is due to insufficient memory, which doesn't seem like the case here but I can't be 100% sure from here, then fiddling with the HDF5 parameters shouldn't have an effect.  It looks more like a naming mismatch or perhaps a corruption in the input HAL file (which happens frequently when downloading massive files from S3).

**Comment by diekhans** [comment]
Note the alignments are now available from a non-S3 server and the 242 way has been correct to remove a duplicated sample that was placed in the wrong part of the tree (now 241-way)

The downloads and MD5 sums are all available from here:
   https://cglgenomics.ucsc.edu/data/cactus/

**Comment by pbandjanet** [comment]
Great, thanks! I will download the corrected alignment and give it a try.

**Comment by pbandjanet** [comment]
That solved the problem. Thanks again for the quick response!
