### ISSUE TITLE
syntenic build

### ISSUE THREAD

**Issue by wuxingbo1986** [ComparativeGenomicsToolkit/hal#176]
Hi, Can halsynteny be used for syntenic build to reconstruct a genome? what are the steps?

Thanks.

**Comment by ksenia-krasheninnikova** [comment]
Dear @wuxingbo1986,

halSynteny has been designed and tested to infer synteny between two genomes. You can have a look at [the paper](https://academic.oup.com/gigascience/article/9/6/giaa047/5848161). If two genomes belong to the same species, you can use one as a reference for a chromosomal assignment in the other. However there are no well defined procedure describing these steps, it would highly depend on the qualities of both assemblies.

Best
