### ISSUE TITLE
Getting Chromosome Sizes from hal File

### ISSUE THREAD

**Issue by imk1** [ComparativeGenomicsToolkit/hal#183]
Is there a way to get the sizes of the chromosomes/scaffolds that were used in creating a Cactus alignment from a hal file?  If so, can you direct me to the tools that I should use?

Thanks!

**Comment by diekhans** [comment]
get the list of genomes:
  halStats --genomes the.hal 

get the list of sequences and sizes:
  halStats --chromSizes somegenome the.hal

**Comment by imk1** [comment]
That seems to work.  Thank you!
