### ISSUE TITLE
Hardcoded UCSC filepath

### ISSUE THREAD

**Issue by dzerbino** [ComparativeGenomicsToolkit/hal#2]
The hal/include.mk file has a UCSC filepath which breaks compilation for other users:

SAMTABIXDIR = /hive/data/outside/samtabix/${MACHTYPE}

There is also:
dataSetsPath=/Users/hickey/Documents/Devel/genomes/datasets

... but I'm guessing this is less critical ;)

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
