### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Tkastylevsky** [ComparativeGenomicsToolkit/hal#205]
Hello there, 
I'm trying to install HAL on a virtual machine. It's worked fine in the past for me, and I'm following your Readme, but suddenly today it stopped working. This is the error.
`In file included from impl/halAlignmentInstance.cpp:12:
mmap_impl/mmapAlignment.h:6:10: fatal error: sonLib.h: No such file or directory
    6 | #include "sonLib.h"
      |          ^~~~~~~~~~`
I checked on the sonLib git and I saw that there was an update just 9 hours ago, might be linked ? 
Have a nice day, 
Timothee

**Comment by Tkastylevsky** [comment]
I tried downgrading sonLib and it worked, btw.

**Comment by glennhickey** [comment]
Good catch, thanks!  The tests here reproduce: https://travis-ci.org/github/ComparativeGenomicsToolkit/hal/jobs/767163790

**Comment by glennhickey** [comment]
Resolved by https://github.com/ComparativeGenomicsToolkit/sonLib/pull/20/commits/40e26b9e2b3bc59baaf3b098facd91654f978919
