### ISSUE TITLE
Coverage differs by --length and --start in maf result of hal2maf

### ISSUE THREAD

**Issue by pskvins** [ComparativeGenomicsToolkit/hal#220]
Hi,
I'm currently extracting hal file (241-way mammalian alignment, update (V2)) from [https://cglgenomics.ucsc.edu/data/cactus/](url) using hal2maf, and tried to extract chromosome 19 of Homo sapiens for the check.

I used hal2maf_split.pl provided by Augustus, which takes the chunk size that splits the chromosome I want to extract by the size I want with using the --start and --length flag.

So I tried to extract chromosome 19 of Homo sapiens with 3 distinct chunk sizes (600000, 617200, 1000000), and I found out that resulted coverages are different. (I'm not 100% sure if I used 617200 or used other sizes because I didn't take note of the several trials I did first, so I took one from the history (still, the sizes I used for the several trials were really close to each other, so it would not cause that much difference).)

(The actual command looks like this: `hal2maf --refGenome Homo_sapiens --noAncestors --refSequence chr19 --targetGenomes Ailuropoda_melanoleuca,Bos_taurus,Callithrix_jacchus,Camelus_ferus,Canis_lupus_familiaris,Capra_hircus,Cavia_porcellus,Ceratotherium_simum,Chinchilla_lanigera,Chlorocebus_sabaeus,Chrysochloris_asiatica,Condylura_cristata,Cricetulus_griseus,Dasypus_novemcinctus,Echinops_telfairi,Elephantulus_edwardii,Eptesicus_fuscus,Equus_caballus,Erinaceus_europaeus,Felis_catus,Gorilla_gorilla,Heterocephalus_glaber,Ictidomys_tridecemlineatus,Jaculus_jaculus,Leptonychotes_weddellii,Loxodonta_africana,Macaca_fascicularis,Macaca_mulatta,Mesocricetus_auratus,Microtus_ochrogaster,Mus_musculus,Myotis_davidii,Myotis_lucifugus,Nomascus_leucogenys,Ochotona_princeps,Octodon_degus,Orcinus_orca,Orycteropus_afer,Oryctolagus_cuniculus,Otolemur_garnettii,Ovis_aries,Pan_troglodytes,Pantholops_hodgsonii,Papio_anubis,Pongo_abelii,Pteropus_alecto,Pteropus_vampyrus,Rattus_norvegicus,Saimiri_boliviensis,Sorex_araneus,Sus_scrofa,Trichechus_manatus,Tupaia_chinensis,Vicugna_pacos --start 600000 --length 600000 /path/to/hal /path/to/maf`)

I calculated the coverage by counting the number of bases from reference species aligned with bases in target species, so excluding the bases from reference species only aligned to the gap or Ns.

As a result, I got 53,613,438 bases aligned for the maf of chunk size 600,000, 53,557,497 for chunk size 617,200, and 53,347,991 for chunk size 1,000,000.

It seems like they show some gaps in the reference sequence aligned to another position of the reference sequence, and the positions of gaps are different for each case. Also, there were some positions where one case could extract, but the other couldn't extract.

Is this something natural to happen using hal2maf or is it some kind of bug?

And is it possible to make the reference sequence not to be aligned to the other reference sequences, so only the target species are aligned to the reference species?

I would really appreciate it if you can help me with it.

Thank you.

**Comment by glennhickey** [comment]
You can try the `--onlyOrthologs` option, which may help with this issue.

**Comment by pskvins** [comment]
That option solved all my problems, thank you for your comment!
