### ISSUE TITLE
Extract single-base alignment for a pair of genomes

### ISSUE THREAD

**Issue by RenzoTale88** [ComparativeGenomicsToolkit/hal#221]
Hello,
I've generate a large HAL file using cactus v1.3.0. 
Is there a way to query the HAL archive for specific positions in one genome and get the aligned base or bases in a second genome using python? (i.e. get genome1.chr1 pos1 in genome2).

Thank you in advance for your help
Andrea

**Comment by diekhans** [comment]
I would use hal2maf to extract specific columns.  Options of interest:

--length <value>:               length of the sequence, requires --refSequence. If
                                set to 0, the entire genome is converted [default =
                                0]
--refGenome <value>:            name of reference genome (root if empty) [default = ]
--refSequence <value>:          name of reference sequence within reference genome
                                (all sequences if empty) [default = ]
--refTargets <value>:           bed file coordinates of intervals in the reference
                                genome to export (or "stdin" to pipe from standard
                                input) [default = ]
--start <value>:                coordinate within the sequence, requires
                                --refSequence [default = 0]
--targetGenomes <value>:        comma-separated (no spaces) list of target genomes
                                (others are excluded) (vist all if empty) [default =
                                ]

**Comment by RenzoTale88** [comment]
@diekhans yes, that is what I have been doing so far, but I was wondering if there was a way to take advantage of the HDF5 format directly to access the same type of data directly from a custom python piece of code. If not, I understand and I'll carry on with the old method

**Comment by diekhans** [comment]
Without using the HAL library directly, the HDF5 structures would require a lot of code
to interpret.  Unless you have tons of time to learn the internals, I would stic  k with
hal2maf ;-)

I would probably stick with hal2maf.  Using a BED to define multiple regions to speed things
up.

good luck!

**Comment by RenzoTale88** [comment]
Thank you, I'll just crack on with the method I got in place then :) Thank you very much!
Andrea
