### ISSUE TITLE
please tag new release version

### ISSUE THREAD

**Issue by EricDeveaud** [ComparativeGenomicsToolkit/hal#233]
Hello,

while building hal with PhyloP support  either from tagged relase version archive (https://github.com/ComparativeGenomicsToolkit/hal/archive/refs/tags/release-V2.1.tar.gz) either from git repo I have different results with `halPhyloP` test 

from git tree. test run OK
```
deb_maker:phyloP/test > pwd
/opt/gensoft/src/hal/hal/phyloP/test
deb_maker:phyloP/test > ../../bin/halPhyloP blanchette.hal HUMAN blanchette.mod fromHal > foo
```

from tagged archive 
```
deb_maker:phyloP/test > pwd
/opt/gensoft/src/hal/hal-release-V2.1/phyloP/test
deb_maker:phyloP/test > ../../bin/halPhyloP blanchette.hal HUMAN blanchette.mod fromHal > foo
hal exception caught: HAL API v2.1 incompatible with format v1.2 HAL file.
```

from both build, binaires claims to be version 2.1

from git repo
```
deb_maker:phyloP/test > pwd
/opt/gensoft/src/hal/hal/phyloP/test
deb_maker:phyloP/test > ../../bin/halPhyloP --help |& head -n3
 

../../bin/halPhyloP v2.1: Make PhyloP wiggle plot for a genome.
```

from release archive.
```
deb_maker:phyloP/test > pwd
/opt/gensoft/src/hal/hal-release-V2.1/phyloP/test
deb_maker:phyloP/test > ../../bin/halPhyloP --help |& head -n3
 

../../bin/halPhyloP v2.1: Make PhyloP wiggle plot for a genome.
```

there is 221 commits since last tagged release, maybee it will a good idea to provide a new release tag. 

regards

Eric

**Comment by glennhickey** [comment]
[OK!](https://github.com/ComparativeGenomicsToolkit/hal/releases/tag/release-V2.2)
