### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by kspham** [ComparativeGenomicsToolkit/hal#27]
It seems that there is no declaration of  stTree_setChild, even in sonLib. 
....
h5c++ -prefix=/home/kspham/pro/DIR/hdf5 -O3 -g -Wall -funroll-loops -DNDEBUG  -I../    /../sonLib/lib -fPIC -I inc -I hdf5_impl -I impl -I ../lib// -c  impl/halMafBed.cpp     impl/halMafBlock.cpp impl/halMafExport.cpp impl/halMafScanDimensions.cpp impl/halM    afScanner.cpp impl/halMafScanReference.cpp impl/halMafWriteGenomes.cpp 
impl/halMafBlock.cpp: In function ‘void prioritizeNodeInTree(stTree*)’:
impl/halMafBlock.cpp:190:34: error: ‘stTree_setChild’ was not declared in this scope

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
