### ISSUE TITLE
specifying a bed interval file for halSnps

### ISSUE THREAD

**Issue by tli71193** [ComparativeGenomicsToolkit/hal#270]
Hi there,

I am wondering if I can specify regions in the reference genome in halSnps rather than go through the entire reference genome to speed things up. 

I see there's an argument --start that may be an option to use but how can i specify an interval rather than the chromosome?

this may be a simple question and maybe I'm just very clueless in knowing how to use the function.

Thanks in advance for the help!

**Comment by diekhans** [comment]
you can use --refSequence, --start, --length to get a region.

It would be nice if this could be a ucsc/samtools style seq:start-end
