### ISSUE TITLE
Speeding up halLiftover

### ISSUE THREAD

**Issue by tli71193** [ComparativeGenomicsToolkit/hal#273]
Hi there,

I was wondering if there is anyone of speeding up halLiftover. I'm essentially converting genome to genome between species and was wondering how I might query the hal file faster.

Any advice would be much appreciated! thanks!

**Comment by glennhickey** [comment]
`--inMemory` always helps if you have enough RAM.  Otherwise, you'd have to manually cut up your bed region, lift each in parallel in a separate process, then combine the result.  @diekhans may be aware of some tooling to help with this?

**Comment by glennhickey** [comment]
Sorry, I should have said `--hdf5InMemory`

```
--hdf5InMemory:               load all data in memory (and disable hdf5 cache) 
                              [default = 0]
```

**Comment by tli71193** [comment]
So can I assume it’s a Boolean parameter? Rather than inputting a value.

**Comment by tli71193** [comment]
I ended up having to manually cut up your bed region, lift each in parallel in a separate process, then combine the result like you said @glennhickey . It def is faster.

Storing it in memory was too much for my current setup. Thanks for all your help!
