### ISSUE TITLE
halLodInterpolate.py --inMemory flag is obsolete but --hdf5InMemory is not recognized

### ISSUE THREAD

**Issue by chenhijy** [ComparativeGenomicsToolkit/hal#284]
Using either the CPU or the GPU quay.io/comparative-genomics-toolkit/cactus:v2.6.8 docker image

**Comment by glennhickey** [comment]
`--inMemory` still works despite the warning about being deprecated. 

But as far as I can tell, the various `halLod` tools do *not* work anymore as they have not been maintained over the years, unfortunately.

**Comment by chenhijy** [comment]
Thanks, Glenn!

**Comment by chenhijy** [comment]
@glennhickey do you have recommendations for achieving faster loading of hal axts via assemblyHubs given the status of halLod tools?

**Comment by glennhickey** [comment]
No, I'm afraid not.  Maybe @diekhans can comment.  For the alignment coverage, you can use `cactus-hal2maf` then `cactus-maf2bigmaf` to make maf+summary tracks that will scale very well.
