### ISSUE TITLE
hal make error

### ISSUE THREAD

**Issue by Marh32** [ComparativeGenomicsToolkit/hal#297]
Hi,
I cd to hal/, enter make, the following error is reported: 
"hdf5_impl/hdf5UDCFuseDriver.cpp:35:10: fatal error: common.h: No such file or directory
   35 | #include "common.h"
      |          ^~~~~~~~~~
compilation terminated.
make[1]: *** [../rules.mk:18: ../objs/api/hdf5_impl/hdf5UDCFuseDriver.o] Error 1
make[1]: Leaving directory '/home/dell/Documents/Repo/hal/api'
make: *** [Makefile:13: api.libs] Error 2"

**Comment by glennhickey** [comment]
Try not defining `ENABLE_UDC`.  You can run `unset ENABLE_UDC` to make sure.
