### ISSUE TITLE
hal2mafMP.py Cannot allocate memory

### ISSUE THREAD

**Issue by bright-hu** [ComparativeGenomicsToolkit/hal#298]
Hello，
When I use hal2mafMP.py, I get an error, “OSError: [Errno 12] Cannot allocate memory”. However, the memory is enough.
The command is “hal2mafMP.py --noDupes --refGenome Scleropages_formosus --refSequence NC_041814.1 --numProc 10 --sliceSize 10 --hdf5InMemory test.hal test.maf” and "hal2mafMP.py --noDupes --refGenome Scleropages_formosus --refSequence NC_041814.1 --numProc 10 --sliceSize 10 test.hal test.maf"

Do you know any solutions to solve this error?
I would appreciate it if you can help me.

**Comment by glennhickey** [comment]
Please see the documentation and examples about MAF exporting here: 

https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/progressive.md#maf-export
