### ISSUE TITLE
halPhyloPMP.py ERROR

### ISSUE THREAD

**Issue by bright-hu** [ComparativeGenomicsToolkit/hal#302]
Hi,
I was running halPhyloPMP.py， the command is 
halPhyloPMP.py --numProc 100 ../504_way.fish.hal Danio_rerio ../step2/all.mod pick.Danio.wig --targetGenomes Arapaima_gigas,Scleropages_formosus,Megalops_atlanticus,Anguilla_anguilla

but I got  “Unrecognized option: --targetGenomes” and lots of halPhyloP help documentation!
the “--targetGenomes” option was in the help documentation of halPhyloPMP.py, how to fix this.

Sincerely

**Comment by bright-hu** [comment]
Also， the final error is
multiprocessing.pool.RemoteTraceback:
"""Traceback (most recent call last):
  File "/public/home/zhengjiangmin/Software/Python_3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker    result = (True, func(*args, **kwds))  File "/public/home/zhengjiangmin/Software/Python_3.9/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar    return list(map(*args))  File "/public/home/zhengjiangmin/Software/cactus/cactus-bin-v2.5.2/lib/hal/stats/halStats.py", line 27, in runShellCommand
    raise RuntimeError("Command: %s exited with non-zero status %i" %
RuntimeError: Command: halPhyloP ../504_way.fish.hal Danio_rerio ../step2/all.mod pick.Danio_halPhyloPTemp4PF74_0.wig --start 0 --length 16791869 --targetGenomes Arapaima_gigas,Scleropages_formosus,Megalops_atlanticus,Anguilla_anguilla,Clupea_harengus,Chanos_chanos,Sinocyclocheilus_anshuiensis,Cyprinus_carpio,Megalobrama_amblycephala,Electrophorus_electricus,Astyanax_mexicanus,Pygocentrus_nattereri,Esox_lucius,Myripristis_murdjan exited with non-zerostatus 1
"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):  File "/public/home/zhengjiangmin/Software/cactus/cactus-bin-v2.5.2/bin/halPhyloPMP.py", line 306, in <module>
    sys.exit(main())  File "/public/home/zhengjiangmin/Software/cactus/cactus-bin-v2.5.2/bin/halPhyloPMP.py", line 303, in main    runParallelSlices(args)  File "/public/home/zhengjiangmin/Software/cactus/cactus-bin-v2.5.2/bin/halPhyloPMP.py", line 166, in runParallelSlices
    runParallelShellCommands(sliceCmds, options.numProc)
  File "/public/home/zhengjiangmin/Software/cactus/cactus-bin-v2.5.2/lib/hal/stats/halStats.py", line 43, in runParallelShellCommands
    result.get(20000000)
  File "/public/home/zhengjiangmin/Software/Python_3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
RuntimeError: Command: halPhyloP ../504_way.fish.hal Danio_rerio ../step2/all.mod pick.Danio_halPhyloPTemp4PF74_0.wig --start 0 --length 16791869 --targetGenomes Arapaima_gigas,Scleropages_formosus,Megalops_atlanticus,Anguilla_anguilla,Clupea_harengus,Chanos_chanos,Sinocyclocheilus_anshuiensis,Cyprinus_carpio,Megalobrama_amblycephala,Electrophorus_electricus,Astyanax_mexicanus,Pygocentrus_nattereri,Esox_lucius,Myripristis_murdjan exited with non-zero
status 1

**Comment by glennhickey** [comment]
Hi.  Unfortunately, `halPhyloPMP.py` has not been well maintained over the years. I'd like to bring it back, but in the meantime I strongly recommend converting to MAF with `cactus-hal2maf` and then running `PhyloP` on the MAF.

**Comment by bright-hu** [comment]
Thanks anyway.

Glenn Hickey ***@***.***> 于2024年4月29日周一 21:38写道：
