### ISSUE TITLE
Error while "make" for hal

### ISSUE THREAD

**Issue by 4ureliek** [ComparativeGenomicsToolkit/hal#31]
Hi,
I am having issues installing hal:
# as sudo, on CentOS machine

Installing with yum: hdf5.x86_64 and hdf5-devel.x86_64

export PATH=DIR/hdf5/bin:${PATH}
export h5prefix=-prefix=DIR/hdf5

And doing this:
git clone git://github.com/benedictpaten/sonLib.git
pushd sonLib && make && popd

cd hal
make
cd api && make all
make[1]: Entering directory `/home/software/hal/api'
cp inc/*.h  ../lib//
rm -f *.o
h5c++  -O3 -g -Wall -funroll-loops -DNDEBUG  -I..//../sonLib/lib -fPIC -I inc -I hdf5_impl -I impl -I ../lib// -c impl/*.cpp hdf5_impl/*.cpp
hdf5_impl/hdf5MetaData.cpp:61:18: error: missing binary operator before token "("
make[1]: *** [../lib//halLib.a] Error 1
make[1]: Leaving directory`/home/software/hal/api'
make: **\* [all.api] Error 2

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
