### ISSUE TITLE
failures during 'make test'

### ISSUE THREAD

**Issue by douglasgscofield** [ComparativeGenomicsToolkit/hal#35]
I'm getting four test failures during `make test`, all under `api/tests`:

```
........................FFF....F.............

There were 4 failures:
1) halColumnIteratorGapTest: tests/halColumnIteratorTest.cpp:596: assert failed
2) halColumnIteratorMultiGapTest: tests/halColumnIteratorTest.cpp:755: assert failed
3) halColumnIteratorMultiGapInvTest: tests/halColumnIteratorTest.cpp:955: assert failed
4) halRearrangementInsertionTest: tests/halRearrangementTest.cpp:246: assert failed
```

Are these expected failures, or might there be something wrong with my build?

**Comment by ErinZhang1998** [comment]
I am getting a similar error

Traceback (most recent call last):
  File "/Users/erinzhang19980101/multalign/hal/api/apiTest.py", line 30, in testAPI
    system("halApiTests")
  File "/Users/erinzhang19980101/multalign/sonLib/bioio.py", line 185, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: halApiTests exited with non-zero status 1

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
