### ISSUE TITLE
hal2assemblyHub.py failure

### ISSUE THREAD

**Issue by tallnuttcsiro** [ComparativeGenomicsToolkit/hal#36]
all29c@aahl-02-mel:~/d/031/31.11$ hal2assemblyHub.py 31.11.hal hub
Traceback (most recent call last):
  File "/OSM/HOME-MEL/all29c/bin/hal/bin/hal2assemblyHub.py", line 24, in <module>
    from jobTree.scriptTree.target import Target
ImportError: No module named jobTree.scriptTree.target

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
