### ISSUE TITLE
Cannot run hal2assemblyHub.py

### ISSUE THREAD

**Issue by tallnuttcsiro** [ComparativeGenomicsToolkit/hal#38]
hal2assemblyHub.py gives this error.
How can jSon be installed so hal can run?
Please provide better instructions. Thanks

from jobTree.scriptTree.target import Target
ImportError: No module named jobTree.scriptTree.target

**Comment by tallnuttcsiro** [comment]
i.e. what does this mean?
If sonLib and HAL are not sister directories, update hal/include and change

sonLibRootPath=${rootPath}/../sonLib

to reflect the directory where you installed sonLib

**Comment by ifiddes** [comment]
You need to have the following repositories in the same parent directory:

https://github.com/glennhickey/hal
https://github.com/benedictpaten/sonLib
https://github.com/benedictpaten/jobTree

Then

export PYTHONPATH=./

Then you should be able to import jobTree and sonLib.

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
