### ISSUE TITLE
hal2maf can output bogus coordinates

### ISSUE THREAD

**Issue by benedictpaten** [ComparativeGenomicsToolkit/hal#4]
Using the hal file at:

/hive/users/benedict/progressiveBenchmarks/outputTenWay_Masking50/tenWayGenomes_rm10_ogGreedy_ot0_saFalse_ktInmemory/tempProgressiveCactusAlignment/progressiveCactusAlignment/out.hal

I generated a maf using:

hal2mafMP.py  --numProc=5 --inMemory --ucscNames --refGenome HUMAN out.hal outHuman.maf

Which is:

/hive/users/benedict/progressiveBenchmarks/outputTenWay_Masking50/tenWayGenomes_rm10_ogGreedy_ot0_saFalse_ktInmemory/tempProgressiveCactusAlignment/progressiveCactusAlignment/outHuman.maf

Using the latest development branch of hal.

I got the block:

a
s HUMAN.chr17_ctg5_hap1          1683575  0 +  1680828 ----
s HUMAN.chr17_gl000203_random       2747  4 +    37498 TATC

(at line 689650902 of the file)

In the output. Note that the human first sequence line refers to a start coordinate outside of the range of the chromosome size, although as the line is all gaps, no actual residue has a clearly wrong coordinate. 

I'm turning this assert of in my code, but it's an odd corner case that might be worth tracking down.

Cheers.

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
