### ISSUE TITLE
Make error for HAL

### ISSUE THREAD

**Issue by jkorstia** [ComparativeGenomicsToolkit/hal#56]
Hello,

I am trying to run the last step of installing HAL (running make in the /hal directory).  I am getting an error that I do not understand.  I am including the full make output and error messages below.  I suspect it is probably a relatively straightforward error I made along the way.  I am quite new at this and would appreciate any help in deciphering and troubleshooting here!

Thanks,
Jenny

compute-24-13:/lustre/scratch/jkorstia/apps/hal$ make
cd api && make all
make[1]: Entering directory `/lustre/scratch/jkorstia/apps/hal/api'
h5c++ -prefix=/lustre/scratch/jkorstia/apps/hdf5 -O3 -g -Wall -funroll-loops -DNDEBUG -I..//../sonLib/lib -fPIC -I inc -I impl -I ../lib/ -I impl -I tests -o ../bin//halApiTests tests/*.cpp ../lib//halLib.a ..//../sonLib/lib/sonLib.a ..//../sonLib/lib/cuTest.a
tests/halGenomeTest.cpp: In function 'void setTopSegments(hal::Genome*, hal_size_t)':
tests/halGenomeTest.cpp:374:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (; topIt->getArrayIndex() < n; topIt->toRight(), startPos += width)
                                 ^
tests/halGenomeTest.cpp: In function 'void setBottomSegments(hal::Genome*, hal_size_t)':
tests/halGenomeTest.cpp:391:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (; bottomIt->getArrayIndex() < n; bottomIt->toRight(), startPos += width)
                                    ^
tests/halGenomeTest.cpp: In function 'void checkBottomSegments(hal::Genome*, hal_size_t, CuTest*)':
tests/halGenomeTest.cpp:496:37: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for (; bottomIt->getArrayIndex() < n; bottomIt->toRight(), startPos += width)
                                     ^
tests/halMappedSegmentTest.cpp: In member function 'virtual void MappedSegmentMapExtraParalogsTest::checkCallBack(hal::AlignmentConstPtr)':
tests/halMappedSegmentTest.cpp:672:8: warning: variable 'found' set but not used [-Wunused-but-set-variable]
   bool found[3] = {false, false, false};
        ^
..//../sonLib/lib/sonLib.a(commonC.o): In function `arrayCopyResize_NoCheck':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:89: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:89: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:89: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:89: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:89: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/sonLib.a(commonC.o):/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:89: more undefined references to `_intel_fast_memcpy' follow
..//../sonLib/lib/sonLib.a(commonC.o): In function `constructRandomDir':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:804: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:807: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:807: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(commonC.o): In function `destructRandomDir':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:831: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(commonC.o): In function `tempFileTree_getTempFile':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:971: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(commonC.o):/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:869: more undefined references to `__intel_sse2_strlen' follow
..//../sonLib/lib/sonLib.a(commonC.o): In function `tempFileTree_getTempFile':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:1007: undefined reference to `__intel_sse2_strcpy'
..//../sonLib/lib/sonLib.a(commonC.o): In function `constructTempFileTree':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:910: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:916: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:917: undefined reference to `__intel_sse2_strcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:924: undefined reference to `_intel_fast_memset'
..//../sonLib/lib/sonLib.a(commonC.o): In function `tempFileTree_getTempFile':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:971: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:1006: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:1007: undefined reference to `__intel_sse2_strcpy'
..//../sonLib/lib/sonLib.a(commonC.o): In function `constructTempFileTree':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:910: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:916: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:917: undefined reference to `__intel_sse2_strcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/commonC.c:924: undefined reference to `_intel_fast_memset'
..//../sonLib/lib/sonLib.a(hashTableC.o): In function `create_hashtable':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/hashTableC.c:55: undefined reference to `_intel_fast_memset'
..//../sonLib/lib/sonLib.a(hashTableC.o): In function `hashtable_expand':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/hashTableC.c:93: undefined reference to `_intel_fast_memset'
..//../sonLib/lib/sonLib.a(sonLibCommon.o): In function `st_setLogLevelFromString':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibCommon.c:55: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibCommon.c:55: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_copy':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:20: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:20: undefined reference to `__intel_sse2_strcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:20: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:20: undefined reference to `__intel_sse2_strcpy'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_getNextWord':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:74: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `string_replaceP':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:83: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_replace':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:108: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:108: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `string_replaceP':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:83: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_replace':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:113: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(sonLibString.o):/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:113: more undefined references to `__intel_sse2_strlen' follow
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_join':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:138: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:141: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:127: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:131: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:137: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:138: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:141: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_copy':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:20: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:20: undefined reference to `__intel_sse2_strcpy'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_getNextWord':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:74: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:74: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_splitByString':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:168: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_getSubString':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:181: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_copy':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:20: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:20: undefined reference to `__intel_sse2_strcpy'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_getSubString':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:181: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/sonLib.a(sonLibString.o): In function `stString_reverseComplementString':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibString.c:249: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(sonLibList.o): In function `st_list_appendP':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibList.c:88: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibList.c:88: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibList.c:88: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibList.c:88: undefined reference to `_intel_fast_memcpy'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibList.c:88: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/sonLib.a(sonLibList.o):/lustre/scratch/jkorstia/apps/sonLib/C/impl/sonLibList.c:88: more undefined references to `_intel_fast_memcpy' follow
..//../sonLib/lib/sonLib.a(stSafeC.o): In function `stSafeCCalloc':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/stSafeC.c:45: undefined reference to `_intel_fast_memset'
..//../sonLib/lib/sonLib.a(stSafeC.o): In function `stSafeCCopyMem':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/stSafeC.c:60: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/sonLib.a(stSafeC.o): In function `stSafeCDynFmtv':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/stSafeC.c:85: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/C/impl/stSafeC.c:85: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/sonLib.a(stSafeC.o): In function `stSafeCErr':
/lustre/scratch/jkorstia/apps/sonLib/C/impl/stSafeC.c:28: undefined reference to `__intel_sse2_strlen'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStrCopy':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:22: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:24: undefined reference to `__intel_sse2_strcpy'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringAppend':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStrCopy':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:22: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:24: undefined reference to `__intel_sse2_strcpy'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringAppend':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringInsert':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:98: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:103: undefined reference to `_intel_fast_memmove'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:105: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringAppend':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringInsert':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:98: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:103: undefined reference to `_intel_fast_memmove'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:105: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringAppend':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringInsert':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:98: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:103: undefined reference to `_intel_fast_memmove'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:105: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringAppend':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringInsert':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:98: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:103: undefined reference to `_intel_fast_memmove'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:105: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringAppend':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringInsert':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:98: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:103: undefined reference to `_intel_fast_memmove'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:105: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuSuiteInit':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:242: undefined reference to `_intel_fast_memset'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringAppend':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringInsert':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:98: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:103: undefined reference to `_intel_fast_memmove'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:105: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuSuiteInit':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:242: undefined reference to `_intel_fast_memset'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringAppend':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:71: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:75: undefined reference to `__intel_sse2_strcat'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStringInsert':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:98: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:103: undefined reference to `_intel_fast_memmove'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:105: undefined reference to `_intel_fast_memcpy'
..//../sonLib/lib/cuTest.a(CuTest.o): In function `CuStrCopy':
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:22: undefined reference to `__intel_sse2_strlen'
/lustre/scratch/jkorstia/apps/sonLib/externalTools/cutest/CuTest.c:24: undefined reference to `__intel_sse2_strcpy'
collect2: error: ld returned 1 exit status
make[1]: *** [../bin//halApiTests] Error 1
make[1]: Leaving directory `/lustre/scratch/jkorstia/apps/hal/api'
make: *** [all.api] Error 2

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
