### ISSUE TITLE
hdf5 Ubuntu package acceptable?

### ISSUE THREAD

**Issue by EmilioGarciaMoran** [ComparativeGenomicsToolkit/hal#58]
My question is whether, just like MacPorts seems ok, the HDF5 support may be enabled by just a sudo apt-get install hdf5..... just in case I am compiling from sourcr. Much more work....

**Comment by glennhickey** [comment]
Should be fine -- just make sure it has the C++ support enabled.  The
README should be updated with an apt-get example.

On Tue, Sep 26, 2017 at 8:57 AM, EmilioGarciaMoran <notifications@github.com

**Comment by EmilioGarciaMoran** [comment]
The theoretical package providing an hdf5 bundle for Linux/Ubuntu does not seem to exist. I have IMHO succeded in the installation of hdf5 in system-wide manner. For this I have started at the likely end of dependencies chain: zlib from zlib.net. 
wget [url to tar.gz at zlib.net]
tar -xvfz tar.source.zlib
cd zlib.....
./configure --prefix=/usr/lib/zlib #a suitable place of a general utility library
sudo make
make install
The optional szip is just likewise, only that source code comes from hdfgroup themselves
In the case of hdf5 ./configure is a little more complex
$ ./configure --prefix=/usr/lib/hdf5 --enable-fortran \
                          --enable-cxx --with-szlib=PATH_TO_SZIP
I had then updated environmental variables appropriately to my paths. How can I be sure hdf5 utilities are installed?. Typing from prompt whereis or which does find them. 
As I have tried to proceed by entering the ---/hal directory and typed sudo make... it starts compilation but after a few lines it says h5c++ is not at /bin/sh..... That program happens to be accessible from command line in my system, final confirmation of the effect of my first steps. ....however I do not know how to make it available to the build process.
I was ready to install ProgressiveCactus as a whole though I just need halLiftover utility. The make process was unsuccessful. gcc python and the rest are ok....
Sorry for the long comment but I have come across serious trouble to set up this software under Linux Ubuntu.

**Comment by glennhickey** [comment]
hal and hdf5 are included in cactus.  if you can build that, you can get
hal tools by sourcing 'progressiveCactus/environment'

https://github.com/glennhickey/progressiveCactus

hdf5 is available via apt (apt-get search libhdf5), but the version I'm
seeing doesn't have a compatible c++ interface with hal, unfortunately.


On Tue, Sep 26, 2017 at 4:46 PM, EmilioGarciaMoran <notifications@github.com

**Comment by diekhans** [comment]
this should be addressed, please reopen if still a problem
