### ISSUE TITLE
[Improvement] CAT failing cryptically if no alignment found for species in HAL

### ISSUE THREAD

**Issue by lucventurini** [ComparativeGenomicsToolkit/hal#61]
I stumbled onto this while trying to subset a HAL file for tests. While trying to do so, I accidentally removed one species out of three from the HAL itself.

Subsequently, CAT failed with errors like the following:

> n61898 2017-12-18 11:23:26,780 MainThread WARNING toil.leader: W/d/jobK9HTGf      File "/usr/users/ga002/venturil/workspace/Comparative-Annotation-Toolkit/cat/align_transcripts.py", line 98, in setup
> n61898 2017-12-18 11:23:26,780 MainThread WARNING toil.leader: W/d/jobK9HTGf        raise RuntimeError(err_msg)
> n61898 2017-12-18 11:23:26,780 MainThread WARNING toil.leader: W/d/jobK9HTGf    RuntimeError: Align Transcripts pipeline did not detect any input genePreds for chr1B

or 

>   File "/usr/users/ga002/venturil/workspace/cactus/cactus_env/lib/python2.7/site-packages/toil/fileStore.py", line 1475, in asyncWrite
>    raise RuntimeError("The termination flag is set, exiting")
> RuntimeError: The termination flag is set, exiting

Ideally, CAT should provide a more informative error (like "No alignment found in HAL for chr1B") and maybe be robust to this (ie, just provide an empty file for the missing genome).

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
