### ISSUE TITLE
hal2maf All Species Named Reference Species

### ISSUE THREAD

**Issue by jerricamae** [ComparativeGenomicsToolkit/hal#71]
I'm attempting to convert a hal file I generated using cactus to a maf file using hal2maf. The maf that is created has all of the species labeled as the reference species, however. The sequences that are aligned are unique however. This is the command I'm executing: hal2maf Carout.hal Carnivorealgn.maf --rootGenome Anc0 --refGenome Dog. So despite the alignments being unique, any sequence that is not an ancestor is labeled as "Dog". I would greatly appreciate any guidance. Thank you.

**Comment by joelarmstrong** [comment]
Hi Jerrica,

Sorry for the delay in replying. Hmm, this seems odd. What is the tree like in Carout.hal? Have you tried without the --rootGenome option? It's definitely possible there is something weird going on with --rootGenome; we usually don't use that option so a bug might have slipped through. However, I've tried to replicate this a few ways and I can't figure out what could be going on. The only way I can get something similar is if I swap --rootGenome and --refGenome, i.e. in your case --rootGenome Dog --refGenome Anc0.

PS: You may want to try adding the --onlyOrthologs option; it'll slightly reduce the number of paralogous alignments you get.
