### ISSUE TITLE
Limiting I/O of halLiftover

### ISSUE THREAD

**Issue by imk1** [ComparativeGenomicsToolkit/hal#74]
I am finding that halLiftover is extremely high on I/O when I have a large input bed file.  I am guessing that this is happening because it reads in one line at a time and writes a mapping as soon as the mapping is identified, meaning that it is constantly producing output (it often finds many mappings for each region because different parts map to different places).  I am wondering if there is a set of options that can limit the I/O.

Thanks so much!

**Comment by diekhans** [comment]
Hi Irene,

The bed file is streamed with buffering on both input and
output, so I doubt that is not the problem.

The --inMemory impacts the behavior of HDF5 and usually improves
performance at a tradeoff for more memory, it is some function
of the size of the HAL file, but I don't have enough experience
to say exactly how much memory would be required.

Is your input BED sorted?  That could make a difference by
improving locality.

I would suggest trying --inMemory.  Although option would be
to split up the BED and running it on multiple computers.

**Comment by imk1** [comment]
My input bed is sorted.  I tried --inMemory, and that did not help.  Increasing --cacheMDC also did not help.

Is there some combination of --cacheBytes, --cacheRDC, and --cacheW0 that might improve performance?  I thought that increasing --cacheBytes and --cacheRDC would help, but that did not seem to have much of an effect.

Would reading from stdin help or hurt performance?

Thanks so much!

**Comment by glennhickey** [comment]
--inMemory should trump any other cache-related options by disabling
caching altogether.  Each genome gets loaded in its entirety from the disk
the first time its accessed and that's it, so I'd expect all I/O to be over
with (at the cost of a large memory footprint) after the first few BED
entries.  Can't really think of why you'd see a sustained I/O bottleneck
with this option.  Are you able to share your input data?

**Comment by imk1** [comment]
I apologize for the confusion and edited my previous message.  --inMemory did solve almost all of the I/O problems.  The problem is that it required so much memory that running 1 hal-liftover job took about 1/4 of the memory on my cluster.  I have to run hundreds of hal-liftover jobs, so I would ideally like to find another solution.

**Comment by glennhickey** [comment]
I see, that makes more sense.  In this case, I think all you can do is try
to increase --cacheRDC and --cacheBytes.  I would suggest increasing the
two of them by about the same factor.   This should help somewhat, but I'm
not sure which, if any, values would get you to the sweet spot you're
looking for.

**Comment by imk1** [comment]
Thanks so much!  I will give that a try and see how it goes.

**Comment by glennhickey** [comment]
As an aside, @diekans, a multithreaded liftover (contingent on --inMemory
being used) may be implementable without too much hassle.  If it's getting
used a lot and there's someone looking for a small project...

**Comment by diekhans** [comment]
If Glenn's advice (he knows HDF5 much better than me) doesn't
work, we also have am experimental branch that stores HAL in an
alternative format on disk.

This is a classic space-vs-size trade-off.  This is called mmap
format, as it is uses memory-mapped I/O directly.  The HAL is *much*
larger, however we have gotten significant improvement in speed on
some operations (like hal2maf).  I suspect HAL liftover will be faster.

Conversion to/from HAL HDF5 is support.  We have also made some
speedup in the HDF5, but probably not significant enough to help
you.

It is experimental, so there is some risk at hitting a bug.

Please mail me directly at markd@ucsc.edu if you want to try
this.

**Comment by imk1** [comment]
Thanks so much for all of the input!  I have now tried 5 different values of --cacheRDC and --cacheBytes, and none of them led to substantial performance improvements.  I will look into whether the machine I am using has space for a much larger Cactus alignment and e-mail you know if I am interested in trying your experimental branch.

**Comment by diekhans** [comment]
Closed due to inactivity,  please reopen if still an issue.
