### ISSUE TITLE
Make error for hal : /bin/sh: 1: h5c++: not found

### ISSUE THREAD

**Issue by krostifangers** [ComparativeGenomicsToolkit/hal#78]
Hello
I tried to install hal and had this problem.
cd hal
sudo make
cd api && make all
make[1] : on entre dans le répertoire « /home/clemaire/hal/api »
cp inc/*.h  ../lib//
rm -f *.o
h5c++  -O3 -g -Wall -funroll-loops -DNDEBUG -I..//../sonLib/lib -fPIC -I inc -I hdf5_impl -I impl -I ../lib// -c impl/*.cpp hdf5_impl/*.cpp
/bin/sh: 1: h5c++: not found
Makefile:21 : la recette pour la cible « ../lib//halLib.a » a échouée
make[1]: *** [../lib//halLib.a] Erreur 127
make[1] : on quitte le répertoire « /home/clemaire/hal/api »
Makefile:10 : la recette pour la cible « all.api » a échouée
make: *** [all.api] Erreur 2

As recommended, I previously installed hdf5 following the procedure "with password" as sudo.
when I manually enter the following command line, it seems to work. 
h5c++  -O3 -g -Wall -funroll-loops -DNDEBUG -I..//../sonLib/lib -fPIC -I inc -I hdf5_impl -I impl -I ../lib// -c impl/*.cpp hdf5_impl/*.cpp
h5c++ is working fine. 
Could you help me, please?
Thank you in advance
Christophe

**Comment by glennhickey** [comment]
Bizarre.  Have you tried running make without "sudo" ?

**Comment by diekhans** [comment]
I believe this is due to sudo rest ricing your path.  There is no reason to compile
HAL as root

**Comment by diekhans** [comment]
this should be addressed, please reopen if still a problem

**Comment by sagitaninta** [comment]
Hi, I have the exact same problem when trying to make hal. So what I did is installing all dependencies, which all work perfectly, also add the locally installed hdf5 path, and do

```
git clone https://github.com/ComparativeGenomicsToolkit/hal.git
cd hal
make
```

And this is what I got:

```
cd api && make libs
make[1]: Entering directory '/dss/dsshome1/lxc06/ra57gih/bin/hal/api'
h5c++ -prefix=~/bin/hdf5-1.10.1 -MM -MT ../objs/api/impl/halValidate.o -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -O3 -g -Wall -funroll-loops -DNDEBUG -I../../sonLib/lib -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -I../api/inc -Iimpl -Iinc -I../liftover/inc -Ihdf5_impl -Immap_impl -c impl/halValidate.cpp >impl/halValidate.depend
/bin/sh: h5c++: command not found
make[1]: *** [../rules.mk:18: ../objs/api/impl/halValidate.o] Error 127
make[1]: Leaving directory '/dss/dsshome1/lxc06/ra57gih/bin/hal/api'
make: *** [Makefile:13: api.libs] Error 2
```
