### ISSUE TITLE
Tag a release version

### ISSUE THREAD

**Issue by lparsons** [ComparativeGenomicsToolkit/hal#80]
I'm looking into creating a [bioconda recipe](https://bioconda.github.io/) for hal and having a stable release version would be very helpful. Would you consider tagging a version as a release (so we have a stable version number and tarball)? Thanks.

**Comment by diekhans** [comment]
We can look into this.  We are close to merging in some new functionality.

**Comment by diekhans** [comment]
Hi @lparsons,  we have tagged release-V2.0 and made a release [release-V2.0 ](https://github.com/ComparativeGenomicsToolkit/hal/releases/tag/release-V2.0 )

Please let us know if you have any problems.  Thanks for making a bioconda receipe.  When you have completed this, please file a ticket to add a mention of bioconda to our README (or even do a PR).
