### ISSUE TITLE
Understanding halAlignmentDepth Output

### ISSUE THREAD

**Issue by imk1** [ComparativeGenomicsToolkit/hal#89]
I am using halAlignmentDepth, and I often find that the output I get at a given base is larger than the number of species in the Cactus file.  Might someone be able to explain why this happens?  Thanks so much!

**Comment by joelarmstrong** [comment]
Hi Irene,

Maybe the ancestral genomes are getting counted? I think the `--noAncestors` option to halAlignmentDepth avoids counting the ancestral genomes. (Maybe that should be the default).

**Comment by imk1** [comment]
I bet that explains it.  If you decide to change that to the default, it would be great if you could post an announcement on the github page.  Thanks for getting back to me!
