### ISSUE TITLE
H5 Exception Error

### ISSUE THREAD

**Issue by imk1** [ComparativeGenomicsToolkit/hal#91]
I am getting the following error when I run halLiftover:

terminate called after throwing an instance of 'H5::DataSetIException'
Aborted

Do you have any idea what might be causing this and how I can fix it?  I am on a Linux cluster with Centos version 6 and gcc version 4.9.2.

Thanks so much!

**Comment by diekhans** [comment]
I am probably going to have to run halLiftover to do it.  Is this on the
600 way ?  Can you send me the command line you are using and input bed?

**Comment by imk1** [comment]
Thanks for getting back to me so quickly!  I was using the 200 mammals Cactus for this run of halLiftover  The bed file is from primary data generated by our lab that we have not yet been made publicly available, so I am not sure if I can share it with you.  However, I just tried an experiment where I took the line in the bed file where the error happened and the surround lines and ran halLiftover on those lines alone, and there was no error.  The original bed file was over 100,000 lines long, and the error occurred on line number 98,193, so I am wondering if the problem had something to do with the size of the file.  Do you think that's possible?

**Comment by diekhans** [comment]
I suspect the size of the file is not the problem, at least not
directly.  It could have to do with access patterns, and not
just one entry.

Could you try doing some binary search to see if you can narrow
down the BED to a small set of records that cause it?  Maybe
start with the last 2000 to see if it happens.  Due to the
behavior of HDF5, it might take more than one record to trigger
it.

**Comment by imk1** [comment]
I isolated the problem to a few thousand lines, which I have put here.  I am mapping these coordinates from macaque to mouse.  It would be great if you could help me figure out what is causing the problem.  Thanks so much!
[halLiftoverTest.txt](https://github.com/ComparativeGenomicsToolkit/hal/files/3616535/halLiftoverTest.txt)

**Comment by diekhans** [comment]
This is caused by a zero-length BED record:
`JSUE03147339.1  2355    2355    peak29747`

We will add code to better check for this and report an error.

**Comment by imk1** [comment]
Thanks so much!

**Comment by imk1** [comment]
I am getting this error again and now using the latest version of hal:
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5Dio.c line 171 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: H5Dio.c line 544 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: H5Dchunk.c line 2050 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: H5Dchunk.c line 3397 in H5D__chunk_lock(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #004: H5Fio.c line 133 in H5F_block_read(): read through page buffer failed
    major: Low-level I/O
    minor: Read failed
  #005: H5PB.c line 742 in H5PB_read(): read through metadata accumulator failed
    major: Page Buffering
    minor: Read failed
  #006: H5Faccum.c line 264 in H5F__accum_read(): driver read request failed
    major: Low-level I/O
    minor: Read failed
  #007: H5FDint.c line 229 in H5FD_read(): driver read request failed
    major: Virtual File Layer
    minor: Read failed
  #008: H5FDsec2.c line 715 in H5FD_sec2_read(): file read failed: time = Mon May 18 22:04:09 2020
, filename = '/pylon5/mc5pihp/ikaplow/vert600/600way.hal', file descriptor = 3, errno = 5, error message = 'Input/output error', buf = 0x5243fc0, total read size = 6199, bytes this sub-read = 6199, bytes actually read = 18446744073709551615, offset = 527696953116
    major: Low-level I/O
    minor: Read failed
terminate called after throwing an instance of 'H5::DataSetIException'

I am using the latest version of hal.  There are no sequences with length 0 in my input bed file.  I tried this with the 200 Mammals Cactus and the 600 Mammals and Birds Cactus and got the same error.

**Comment by diekhans** [comment]
Hi Irene,

What command is create things.

Mark

**Comment by diekhans** [comment]
please send exact command you are running?

**Comment by imk1** [comment]
/pylon5/mc5pihp/ikaplow/hal/bin/halLiftover --bedType 4 /pylon5/mc5pihp/ikaplow/vert600/600way.hal Rattus_norvegicus [rat bed file name] Monodon_monoceros [lifted bed file name]

**Comment by imk1** [comment]
The gcc version is 5.3.0.

**Comment by diekhans** [comment]
Hi Irene,

I don't get an error; could you make your rat BED file available?

**Comment by imk1** [comment]
Thanks so much for being so responsive!

The job that I described now works.  In fact, if I run a few jobs at a time, all of them work.  However, if I run a few hundred jobs at a time, many of them start producing this error.  Do you know why that might be?  Thanks!

**Comment by imk1** [comment]
[ratEnhancers.txt](https://github.com/ComparativeGenomicsToolkit/hal/files/4657143/ratEnhancers.txt)

**Comment by diekhans** [comment]
It runs fine for me

The good part, here are your mapped regions:

   https://hgwdev.gi.ucsc.edu/~markd/tmp/ratEnhancers.Monodon_monoceros.txt.gz

the bad part, we still don't know what the problem.

It could be a bug with the version of HDF5, I have 1.8.12.  Maybe a
compiler bug.

You try the pre-compiled hal tools that come with cactus

  https://github.com/ComparativeGenomicsToolkit/cactus/releases/download/v1.0.0/cactus-bin-v1.0.0.tar.gz


Also, your 600way HAL might corrupt.  Here is the md5 on mine:

      8dcf28e4d475db4af66caa026090e10e  600way.hal

**Comment by imk1** [comment]
Thanks for helping me figure this out.  The problem does not seem to occur if I have < 200 halLiftover jobs running at once.  If I need to run more, I will try upgrading my hdf5.

**Comment by diekhans** [comment]
Given the symptoms, I suspect that this is caused by running
more jobs somehow overloading your file server and it reporting
errors to HDF5.

Note the message has errno = 5, which is Input/output error

**Comment by imk1** [comment]
I would not be surprised if you are right.
