### ISSUE TITLE
halLiftover --outPSL broken

### ISSUE THREAD

**Issue by joelarmstrong** [ComparativeGenomicsToolkit/hal#93]
Sometime between master and `ba67c060996ccb1544799a1a85487a271fa59633` the `--outPSL` option to halLiftover stopped working properly. This breaks the CAT chaining step.

**Comment by diekhans** [comment]
I am sure this is me.  What does not work properly look like? Crash and burn or bad output?

**Comment by joelarmstrong** [comment]
I think it just outputs the default BED output.

**Comment by diekhans** [comment]
Working on adding tests now.  AFAIK, PSL doesn't actually work
with unless you have BED12 as input.

**Comment by diekhans** [comment]
The outPSL flag was getting lost.  This is fixed and tests were added.
