### ISSUE TITLE
Make error - 'api.libs' failed

### ISSUE THREAD

**Issue by tobsecret** [ComparativeGenomicsToolkit/hal#94]
Tried to follow the instructions for installing and ran into this error:
```
cd api && make libs
make[1]: Entering directory '/home/tobias/projects/aim2/hal/api'
h5c++  -MM -MT ../objs/api/impl/halAlignmentInstance.o -O3 -g -Wall -funroll-loops -DNDEBUG -I../../sonLib/lib -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -I../api/inc -Iimpl -Iinc -I../liftover/inc -Ihdf5_impl -Immap_impl -c impl/halAlignmentInstance.cpp >impl/halAlignmentInstance.depend
/bin/sh: 1: h5c++: not found
../rules.mk:17: recipe for target '../objs/api/impl/halAlignmentInstance.o' failed
make[1]: *** [../objs/api/impl/halAlignmentInstance.o] Error 127
make[1]: Leaving directory '/home/tobias/projects/aim2/hal/api'
Makefile:13: recipe for target 'api.libs' failed
make: *** [api.libs] Error 2
```

**Comment by glennhickey** [comment]
`/bin/sh: 1: h5c++: not found`  means HDF5 wasn't installed properly (or isn't in your path or doesn't have the c++ API enabled).  There are some notes on installing it in the README.  It can also be built as part of the Cactus install https://github.com/ComparativeGenomicsToolkit/cactus/

**Comment by tobsecret** [comment]
Thanks for the reply! 
Hmmm, that's odd - I tried following the `From Source:` instructions:
```
wget http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz
tar xzf hdf5-1.10.1.tar.gz
cd hdf5-1.10.1
./configure --enable-cxx
make && make install
```
I managed to install cactus previously but the reason I am trying to install this again is because I need to install hal2vg, which did not work, so now I am instead trying to install hal2sg and sg2vg.

**Comment by diekhans** [comment]
It sounds like h5c++ is not on your PATH.  Try:

   which h5c++

**Comment by tobsecret** [comment]
Aaah, thanks!
I hadn't realized that the following bit applied to both installation from source and local installation from source into DIR (I didn't quite get what DIR was supposed to be, I assume it refers to the parent directory of hal?):

>Before building HAL, update the following environment variables:
```
export PATH=DIR/hdf5/bin:${PATH}
export h5prefix=-prefix=DIR/hdf5
```
