### ISSUE TITLE
hal2fasta

### ISSUE THREAD

**Issue by ashlingcha** [ComparativeGenomicsToolkit/hal#98]
Hello,
I'm trying to extract out .fasta files using hal2fasta but looking into the documentation it says:

USAGE:
```
./hal2fasta [Options] <inHalPath> <genome>

ARGUMENTS:
inHalPath:   input hal file
genome:      genome to export
```

And im unsure of what to specify when it comes to genome - because when I've created my hal file I'm just trying to extract them from the cactus example where the tree is: `((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974):0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303):0.032898)
`
So i tried:
`./hal2fasta /group/pawsey0263/ashling_charles/cactus/examples/evolverMammals.hal simHuman_chr6`
but got this output: 
`hal exception caught: Genome simHuman_chr6 not found`

so is the fasta specification not the names you inputted into the seqfile to define each species? or is it something else

hope someone is able to clear this up for me, just a little confused.

Thanks in advance,
Ashling

**Comment by glennhickey** [comment]
`halStats` will list the genome names in the file. 
```
halStats ./examples/evolverMammals.hal

hal v2.1
((simHuman_chr6:0.144018,(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr:0.271974)Anc1:0.020593,(simCow_chr6:0.18908,simDog_chr6:0.16303)Anc2:0.032898)Anc0;

GenomeName, NumChildren, Length, NumSequences, NumTopSegments, NumBottomSegments
Anc0, 2, 545005, 9, 0, 14479
Anc1, 2, 569616, 6, 16878, 54043
simHuman_chr6, 0, 601863, 1, 53501, 0
mr, 2, 611582, 3, 52367, 55582
simMouse_chr6, 0, 636262, 1, 56170, 0
simRat_chr6, 0, 647215, 1, 55693, 0
Anc2, 2, 577038, 15, 17352, 57120
simCow_chr6, 0, 602619, 1, 56311, 0
simDog_chr6, 0, 593897, 1, 55982, 0
```

`simHuman_chr6` is listed in my hal, so it runs through

```
hal2fasta ./examples/evolverMammals.hal simHuman_chr6

>simHuman.chr6
TCTTTCTGGTGCAATAGCCAATCTGCAAACAGTTTCAAGATGAGCACACCTTATATGACTATCAAGCATACAGTCTTGCC
TAGCACACAATCTTGCATTAGATTGTACAATCTCTCGTTCTGGGAGTCAGAGACCAAAGTACCTACTGTGTGGTTGATCG
GGTATCCTGGAGTGTTGGTACTCTAGATTAAATAAAAATGCACACCAGATGTTCCTACAGCCAGGTATACCTGATTGAGA
ACTTCCTGAATAATGGTGTGCTCAGGGAGCTCTATACAGTCTCTACATTGGGGAACTTGGGAAAACTGTTGAACTTACAA
ATCACTTTTAACCAAGCATAAAGTACAGATAGTGCACGTTTCCCTTGGACATGAACAATGCTACCACTGCCCCACTAATA
TTTATGTGACTATAAGATAATTGATGAGCCGAAGTTGCTAGAACAATTAAGTAAGAGCCCCTAAGCATCCTTAAAGCAGT
GAGATATGACCTGCAATTCAAGACAATCCACTTGCCTGATCTGGGTATATTTTGCAATGCTACAGATCTGCTCTAGTTTG
GAGAATTGAGTGCCACAGATGCATCAAATGCTTAGAGTCTCATGAACACTACCCACATTGCTTATTGTACAGGTAGAAAA
TTGGTGACCAGAACTACACCCACCCATCATTGGTACTCTTTCCAAGGCCTTAAaactagaagagttaccactgaattaga

etc etc.
```
```

**Comment by ashlingcha** [comment]
Thanks for that.
For some reason my halStats output for the evolverMammals.txt is: 
`hal v2.1
(simMouse_chr6:0.084509,simRat_chr6:0.091589)mr;

GenomeName, NumChildren, Length, NumSequences, NumTopSegments, NumBottomSegments
mr, 2, 611645, 3, 0, 55562
simMouse_chr6, 0, 636262, 1, 56154, 0
simRat_chr6, 0, 647215, 1, 55669, 0`

would this be a fault with hal or cactus?

Thanks.

**Comment by glennhickey** [comment]
Maybe you specified "mr" as the root when running cactus?

**Comment by diekhans** [comment]
can you put your hal file somewhere that I can download it and I will take a look

**Comment by ashlingcha** [comment]
[evolverMammals.hal.zip](https://github.com/ComparativeGenomicsToolkit/hal/files/4126317/evolverMammals.hal.zip)
I've parsed the .hal file and had a look - but it seems there's just the mouse and rat in there so it's not the hal package.

**Comment by glennhickey** [comment]
Perhaps this is related to https://github.com/ComparativeGenomicsToolkit/cactus/commit/1731c5b8d808b3a84f6333ef37b67bd88c50e3bb
I remember seeing something going by on slack where @joelarmstrong was seeing subtrees get clobbered in the output due to a recent bug where something would be opened for writing instead of appending. 

On a somewhat related note:  @joelarmstrong @diekhans can you please start making changes to cactus via pull requests instead of committing directly to master?  It'd make it a lot easier for others to keep track of what's going on.

**Comment by diekhans** [comment]
it looks like @glennhickey hit it on the nail on the head.  Please update cactus and rebuild.

Please do a submodule deinit, followed by a submodule update --init, as the fix is in the cactus2hal

**Comment by ashlingcha** [comment]
The newest version of cactus isn't building - when I try to make it I get the error:
```
make[3]: Entering directory '/group/pawsey0263/ashling_charles/cactus/submodules/hal/api'
h5c++  -MM -MT ../objs/api/impl/halAlignmentInstance.o -D_GLIBCXX_USE_CXX11_ABI=1 -O3 -g -Wall -funroll-loops -DNDEBUG -I../../sonLib/lib -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11 -Wno-sign-compare -I../api/inc -Iimpl -Iinc -I../liftover/inc -Ihdf5_impl -Immap_impl -c impl/halAlignmentInstance.cpp >impl/halAlignmentInstance.depend
/bin/sh: h5c++: command not found
../rules.mk:17: recipe for target '../objs/api/impl/halAlignmentInstance.o' failed
make[3]: *** [../objs/api/impl/halAlignmentInstance.o] Error 127
make[3]: Leaving directory '/group/pawsey0263/ashling_charles/cactus/submodules/hal/api'
Makefile:13: recipe for target 'api.libs' failed
make[2]: *** [api.libs] Error 2
make[2]: Leaving directory '/group/pawsey0263/ashling_charles/cactus/submodules/hal'
Makefile:151: recipe for target 'suball.hal' failed
make[1]: *** [suball.hal] Error 2
make[1]: Leaving directory '/group/pawsey0263/ashling_charles/cactus'
Makefile:32: recipe for target 'all' failed
make: *** [all] Error 2
```
any suggestions?

**Comment by diekhans** [comment]
We no longer have use a private copy of the HDF5 tool kit.
Install it through your operating system's package manager.

It can also easy to build if you can't install (instructions in HAL README.md).  You need the
HDF C++ support as well.

**Comment by ashlingcha** [comment]
I'm trying to do python setup.py install --prefix=$PWD (I know cactus has recently converted to python 3 so I'm using that version) but I get this error:
```
File "/pawsey/sles12sp3/apps/gcc/4.8.5/python/3.6.3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pip', 'install', 'submodules/sonLib']' returned non-zero exit status 1.
```
Is there a way to find out what is going wrong or does anyone know?
thanks

**Comment by diekhans** [comment]
We backed out the PY3 from master due to problems not detected by the tests.
